### ISSUE TITLE
Epic: `init`, `activate`, and `deactivate` cleanup

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#11308]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

The `init`, `activate`, and `deactivate` have a number of outstanding issues that are reoccurring and/or high-time it gets addressed.

### Proper argparsing for `conda activate` et al. and general implementation cleanup
- https://github.com/conda/conda/issues/6249
- https://github.com/conda/conda/issues/10748

### Fully remove the deprecated `conda.cli.activate`
- https://github.com/conda/conda/issues/6353
- https://github.com/conda/conda/issues/7613

### Resolve outstanding `conda init` items
- https://github.com/conda/conda/issues/7730
- https://github.com/conda/conda/issues/7781
- https://github.com/conda/conda/issues/7843
- https://github.com/conda/conda/issues/8135

### Resolve outstanding subshell items
- https://github.com/conda/conda/issues/7753
- https://github.com/conda/conda/issues/7980
- https://github.com/conda/conda/issues/8536
- https://github.com/conda/conda/issues/10142

### Return codes
- https://github.com/conda/conda/issues/7995
- https://github.com/conda/conda/issues/10182

### csh/tcsh
- https://github.com/conda/conda/issues/8883
- https://github.com/conda/conda/issues/9304
- https://github.com/conda/conda/issues/10707

**Comment by jaimergp** [comment]
Can we add this issue about CMD? https://github.com/conda/conda/issues/11519

**Comment by alikhuseynov** [comment]
Hi there, I'm having issue with `conda activate`. The problem came after I installed locally R package that I dowloaded from [bioconda](https://anaconda.org/bioconda/r-harmony/files) and now after `conda activate my_env` on HPC cluster it give this:
```
This package can only be used in conda-build
Connection to clusterxxx is closed.
```
any suggestions?
Many Thanks

**Comment by jaimergp** [comment]
@alikhuseynov Please open another issue following the template provided for bugs. Your environment contains a package not meant for end-users, hence the error, but we need more details to know which (hence why I suggest following the bug template for new issues). Thanks!
