### ISSUE TITLE
Ensure conda uses inclusive language

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#11517]
### Description

In order to create a welcoming environment for our community, we want to make sure this repository uses inclusive language and avoids problematic terms such as "master" for branch names or "whitelist"/"blacklist" for variable names.

### Linked Issues & PRs

- [x] https://github.com/conda/conda/pull/11570
- [x] Rename `master` branch to `main`
- [x] https://github.com/conda/conda/pull/11645
- [x] https://github.com/conda/conda/pull/11647
- [x] Rename any variables named `black*` to `deny*` (not present)
- [x] Fix ReadTheDocs config to make sure code is pulled from the correct branch (@jezdez)
- [x] Announcements need to be made in all public channels (conda slack team and conda-forge gitter) with instructions on how people can update their local development environments
    - @kenodegard: this may not be necessary since GitHub redirects/announces this for us, see https://github.com/github/renaming
    - [x] @jezdez done for the master/main change in conda/conda

**Comment by travishathaway** [comment]
Here's a good how-to article describing how to rename the "master" branch to "main". It requires the appropriate rights in GitHub to complete though:

https://www.git-tower.com/learn/git/faq/git-rename-master-to-main/

**Comment by travishathaway** [comment]
It's important to note that only org owners can make the necessary updates to this repository in order to complete this issue.

**Comment by travishathaway** [comment]
It's important to note that only org owners can make the necessary updates to this repository in order to complete this issue.

**Comment by travishathaway** [comment]
It's important to note that only org owners can make the necessary updates to this repository in order to complete this issue.

**Comment by jezdez** [comment]
Hey @travishathaway, do you think we could make this ticket an epic and try to tackle each item listed above separately (since some are admin-style tasks and some are code changes needed)?

**Comment by jezdez** [comment]
(delete duplicate comments as https://github.com/conda/conda/issues/11517#issuecomment-1153808221)

**Comment by kenodegard** [comment]
Actually, the process of renaming master to main is even easier thanks to GitHub: https://github.com/github/renaming

It's just a matter of doing the rename in the GitHub web interface and the rest gets done for us.
