### ISSUE TITLE
Unhelpful/Incorrect `UnsatisfiableError`

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#11555]
### Summary

We have long been aware of the cryptic `UnsatisfiableError` messages which are often long, convoluted, and often simply misleading if not outright incorrect.

### Linked Issues & PRs

- [ ] https://github.com/conda/conda/issues/11546
- [ ] https://github.com/conda/conda/issues/11488
- [ ] https://github.com/conda/conda/issues/11382
- [ ] https://github.com/conda/conda/issues/11177
- [ ] https://github.com/conda/conda/issues/10769
- [ ] https://github.com/conda/conda/issues/10672
- [ ] https://github.com/conda/conda/issues/10562
- [ ] https://github.com/conda/conda/issues/10544  <-- possible speedup
- [ ] https://github.com/conda/conda/issues/10443
- [ ] https://github.com/conda/conda/issues/10421
- [ ] https://github.com/conda/conda/issues/10392
- [ ] https://github.com/conda/conda/issues/10324
- [ ] https://github.com/conda/conda/issues/10247
- [ ] https://github.com/conda/conda/issues/10211
- [ ] https://github.com/conda/conda/issues/10206
- [ ] https://github.com/conda/conda/issues/10152
- [ ] https://github.com/conda/conda/issues/10136
- [ ] https://github.com/conda/conda/issues/10123
- [ ] https://github.com/conda/conda/issues/10079
- [ ] https://github.com/conda/conda/issues/10034

**Comment by andygikling** [comment]
This is table stakes for package management software folks.  We really, really need to prioritize getting this sorted out.
