### ISSUE TITLE
Request to add Cisco Umbrella Root CA to signer certificate store

### ISSUE THREAD

**Issue by naatje80** [conda/conda#11563]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

Our company recently enabled "SSL/TLS/HTTPS inspection" for the Cisco Umbrella. This is a feature of there "Intelligent Proxy" service, which is part of Cisco Umbrella. By enabling this, all HTTPS traffic is decrypted for inspection and forwarded to the receiver. Unfortunately, the HTTPS traffic is now signed by the Cisco Umbrella signer corticate, which is not part of the signer certificate database of the conda package manager. A temp. workaround is to disable ssl_verification, but I would like to know if it would be possible include the ROOT CA of Cisco Umbrella to the certificate database. I know that there are also solutions to create your own keystore and use this keystore for verification instead. However, this would require manual work to keep this keystore up-to-date.

### Why is this needed

Automatic verification of HTTPS traffic signed by Cisco Umbrella Intelligent Proxy service

### What should happen?

It would be nice if the Cisco Umbrally ROOT CA, which is available on the following page, https://www.cisco.com/security/pki/, could be added to the signer certificate keystore.

**Comment by sandersn80** [comment]
Any thoughts regarding this topic?

**Comment by sandersn80** [comment]
Please keep this topic open, because it has not been fixed. Could someone please comment on this topic?

**Comment by dholth** [comment]
The best way to solve this would be to use the system's certificate store, which should have your corporate trust, which is something others in the Python http ecosystem have worked on.

**Comment by dholth** [comment]
https://github.com/conda/conda/pull/12361 is a proof-of-concept that uses `truststore` to get certificates. Currently it borrows from pip's implementation, and pip must also be installed.

**Comment by travishathaway** [comment]
Look into OpenSSLv3's ability to read from the Windows cert store.

**Comment by dholth** [comment]
Should be fixed via #13075

Try setting `ssl_verify: truststore` on conda 23.9, available soon.
