### ISSUE TITLE
Release 4.14.0

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#11653]
### Tasks

- [x] [Complete outstanding PRs](https://github.com/conda/conda/milestone/55)
- [x] https://github.com/conda/conda/pull/11668
- [x] [Publish release](https://github.com/conda/conda/releases/tag/4.14.0)
- [x] Create `4.14.x` branch
- [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/9
    - [x] https://github.com/conda-forge/conda-feedstock/pull/171
- [x] Handoff to Anaconda packaging team
- [x] Announce release to Twitter
- [x] Publish `conda rename` blog post

**Comment by LtDan33** [comment]
We should add the `rename` command blog post to this list. (Probably at the end)

**Comment by thesofakillers** [comment]
How do I install this release? Seems like the installer is still at 4.12

**Comment by kenodegard** [comment]
@thesofakillers unfortunately, conda 4.14 is not available on main or conda-forge yet

regarding the installers, please refer to https://github.com/conda/conda/issues/11728

**Comment by kenodegard** [comment]
`conda 4.14.0` is now available on both `main` and `conda-forge`.
