### ISSUE TITLE
Remove the conda project wiki

### ISSUE THREAD

**Issue by LtDan33** [conda/conda#11665]
### What is the idea?

The [conda wiki](https://github.com/conda/conda/wiki) is outdated with some pages being 5+ years old. We should take the valuable info and move it to the docs, and remove the stale info to avoid any confusion. Removing the wiki in general is an option.

### Why is this needed?

Avoid confusion for contributors or those looking for info.

### What should happen?

The wiki should be removed and perhaps just have a link to our various docs. 

### Tasks

- [x] [CEP 0](https://github.com/conda/conda/wiki/CEP-0:-Conda-Enhancement-Proposals)
- [x] [CEP 1](https://github.com/conda/conda/wiki/CEP-1:-Replacing-root-environment-with-default-environment)
- [x] [CEP 2](https://github.com/conda/conda/wiki/CEP-2:-Renaming-packages)
- [x] [Conda Community](https://github.com/conda/conda/wiki/Conda-Community)
- [x] [config](https://github.com/conda/conda/wiki/config)
- [x] [Developer FAQ](https://github.com/conda/conda/wiki/Developer-FAQ)
- [x] [Experiments on conda's version ordering](https://github.com/conda/conda/wiki/Experiments-on-conda's-version-ordering)
- [x] [VC features](https://github.com/conda/conda/wiki/VC-features)

**Comment by jezdez** [comment]
I concur with the long-term plan to just disable the wiki for the conda/conda repo, possibly for other repos as well. It might be useful to review the others and maybe move this ticket into the conda/infra repo, in case we find more wikis 😬

**Comment by kenodegard** [comment]
| Wiki Page | What to do with it | Thoughts |
|---|---|---|
| [CEP 0](https://github.com/conda/conda/wiki/CEP-0:-Conda-Enhancement-Proposals) | delete | superseded by the new [CEP 0](https://github.com/conda-incubator/ceps/blob/main/cep-0.md) and [CEP 1](https://github.com/conda-incubator/ceps/blob/main/cep-1.md) |
| [CEP 1](https://github.com/conda/conda/wiki/CEP-1:-Replacing-root-environment-with-default-environment) | delete | at its core this is the same idea https://github.com/conda/conda/issues/11342, I have copied this over for posterity |
| [CEP 2](https://github.com/conda/conda/wiki/CEP-2:-Renaming-packages) | move | this is an interesting proposal, we should move it over to [CEPs](https://github.com/conda-incubator/ceps) and leave it as a draft for posterity, if someone wants to advocate for this in the future they're welcome to adopt it and continue working on it @jezdez |
| [Conda Community](https://github.com/conda/conda/wiki/Conda-Community) | ??? | this belongs on conda.org, where do we put it in the meantime? do we add a table to one of our READMEs? @tnabtaf |
| [config](https://github.com/conda/conda/wiki/config) | ??? | this is potentially useful info for https://github.com/conda/conda/issues/11662 @ForgottenProgramme @kathatherine | 
| [Developer FAQ](https://github.com/conda/conda/wiki/Developer-FAQ) | delete | not useful |
| [Experiments on conda's version ordering](https://github.com/conda/conda/wiki/Experiments-on-conda's-version-ordering) | ??? | this is a detailed study that explains why we needed to use a PEP440 compatible version for our canary builds https://github.com/conda/conda/pull/11681, not sure where we should put this, this issue https://github.com/conda/conda/issues/4962 gave an interesting finality to the topic @chenghlee @jezdez  |
| [VC features](https://github.com/conda/conda/wiki/VC-features) | ??? | this seems irrelevant to the conda org, this is Anaconda distro stuff, correct? @chenghlee |

**Comment by ForgottenProgramme** [comment]
Hey, @kenodegard 
Thanks for the tag. 
I went through the wiki page you linked, IIUC this was written _before_ `conda config` was created? 
If that's the case, do we still want to keep it in the wiki?  Or maybe we can update this page saying that `conda config` was implemented and these are its features.

**Comment by kenodegard** [comment]
@ForgottenProgramme you're right this is just historical context, up to you and @kathatherine on whether it's valuable to keep, note that the purpose of this issue is an attempt to determine if/how we can remove/disable the wiki

**Comment by tnabtaf** [comment]
@kenodegard The [Conda Community page](https://github.com/conda/conda/wiki/Conda-Community) does have cool stuff on it. And yes, this should go on conda.org.  In the meantime I have made a local copy of it in my conda.org planning directory.

**Comment by kathatherine** [comment]
@ForgottenProgramme @kenodegard It's hard to say if it's valuable or not, especially since I don't know how much this information has changed in nearly 10 years in regards to `git config`. Most of the info stated can be found in `git config help` in some way, so we'd just need to make note of the command somewhere. I'm not sure how much of this we ended up emulating in `conda config` after this was written, if any. If we feel like we might update `conda config` more someday to be more like `git config` maybe it's worth keeping just for the thoughts within?

**Comment by ForgottenProgramme** [comment]
@kenodegard, for [Experiments on conda's version ordering](https://github.com/conda/conda/wiki/Experiments-on-conda's-version-ordering), maybe we can create a GitHub issue 'Use PEP440 compatible version for our canary builds' and add the information from this wiki in the description of that issue (crediting the original author). Then we say that this issue was closed via your PR #11681 .

**Comment by LtDan33** [comment]
`VC features` isn't something that is relevant to conda, and the only part at the end is a really old feature request that has more to do with conda-build, but not really helpful.
So I don't think this page adds much (if any) value.

**Comment by chenghlee** [comment]
In addition to what @LtDan33 mentioned, [Anaconda's Python recipes](https://github.com/AnacondaRecipes/python-feedstock/blob/master/recipe/meta.yaml) no longer use `track_features`, so it's mostly historical information at this point. It should be safe to remove.

**Comment by ForgottenProgramme** [comment]
> @kenodegard, for [Experiments on conda's version ordering](https://github.com/conda/conda/wiki/Experiments-on-conda's-version-ordering), maybe we can create a GitHub issue 'Use PEP440 compatible version for our canary builds' and add the information from this wiki in the description of that issue (crediting the original author). Then we say that this issue was closed via your PR #11681 .

https://github.com/conda/conda/issues/11721

**Comment by ForgottenProgramme** [comment]
- [ ] [CEP 0](https://github.com/conda/conda/wiki/CEP-0:-Conda-Enhancement-Proposals)
- [ ]  [CEP 1](https://github.com/conda/conda/wiki/CEP-1:-Replacing-root-environment-with-default-environment)
- [ ]  [CEP 2](https://github.com/conda/conda/wiki/CEP-2:-Renaming-packages)
- [ ]  [Conda Community](https://github.com/conda/conda/wiki/Conda-Community)
- [ ]  [config](https://github.com/conda/conda/wiki/config)
- [ ]  [Developer FAQ](https://github.com/conda/conda/wiki/Developer-FAQ)
- [ ]  [Experiments on conda's version ordering](https://github.com/conda/conda/wiki/Experiments-on-conda's-version-ordering)
- [ ]  [VC features](https://github.com/conda/conda/wiki/VC-features)

**Comment by LtDan33** [comment]
@ForgottenProgramme Great! Since all these have been accounted for I'm going to remove the wiki and close this ticket.
