### ISSUE TITLE
Conda Commands Audit

### ISSUE THREAD

**Issue by ForgottenProgramme** [conda/conda#11662]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

The idea behind this audit is to ensure that we know what each conda command does and that the documentation on each of these commands is up to date. 
The way @kathatherine and I initially plan to do it is:

1. Run and use each of the conda commands listed in the [documentation](https://docs.conda.io/projects/conda/en/latest/commands.html) and understand what it does and whether it is the same as what the documentation says it does.
2. run `--help` for each command and see whether the purpose and usage of each option are listed and documented.
3. Find commands missing from the documentation and document them. 
4. Find commands mentioned in the documentation but missing in the list rendered by `conda --help` 

### Linked Issues & PRs

- [ ] #

**Comment by travishathaway** [comment]
I would also add that we should be mindful of what commands may be marked as "experimental" that actually shouldn't be. I know that @kathatherine  and I have run across this before.

**Comment by ForgottenProgramme** [comment]
We also have to try and figure out what Experimental exactly means. :))

**Comment by ForgottenProgramme** [comment]
![tempfiles-cli-help](https://user-images.githubusercontent.com/65779580/182127781-43d3f13f-e22b-40a4-b636-434bb5639c4f.png)

The CLI help for `conda clean --tempfiles` is a bit confusing

**Comment by ForgottenProgramme** [comment]
For **conda compare**

**Comment by ForgottenProgramme** [comment]
For conda **rename** 

This command is mentioned in the [docs](https://docs.conda.io/projects/conda/en/latest/commands/rename.html) even though the `conda rename` has not yet been released in the latest conda version.

**Comment by kathatherine** [comment]
For conda list:

[ ] The main definition should be changed to "List installed packages in a conda environment." to be more clear and correct.
[ ] Add an example to the regex flag definition?
[ ] --cannonical - does "Implied --no-pip" mean that using that flag requires the no-pip flag or it will use that flag regardless of whether or not it's specified or some third thing?
[ ] The example in --full-name means nothing to me.
[ ] Typo in --explicit - should be "packages" instead of "packaged"
[ ] --md5 needs period at the end
[ ] --export - No idea what "output requirement string only" means

**Comment by ForgottenProgramme** [comment]
For **conda compare**

1. It is not clear that "environment.yml" is actually the path to the `environment.yml` file.
![image](https://user-images.githubusercontent.com/65779580/182303171-9f72ca22-c684-47a4-8195-bfcb4c7fab76.png)

**Comment by ForgottenProgramme** [comment]
For **conda create**

1.  `--experimental-solver` ,which lets the user use the libmamba solver, is mentioned in docs but doesn't appear in CLI help. (Or is it because I have an older version of conda? @kathatherine  could you please check? )

**Comment by ForgottenProgramme** [comment]
For **conda info**

1. `-q` , `--quiet` is mentioned in the arguments list for `conda info`. But `conda info` just displays information and doesn't make use of `-q`.

**Comment by kathatherine** [comment]
For conda package

- [ ] Is this still experimental?
- [ ] It'd be great to have slightly more info in the opening description of the command.
- [ ]  --which flag description needs rewriting to be more clear
- [ ] In what way are --pkg-name, --pkg-version, and --pkg-build used?

**Comment by kathatherine** [comment]
For conda remove

- [ ] Double dash should be a comma instead in the opening description.
- [ ] Also, there seems to be a "Options:" line with nothing beneath it, unless it's meant to be for the command usage just below it.
- [ ] In --dev, should be "a new conda source"
- [ ] Is `conda remove --all` while in an environment the same as `conda remove -n ENV`, with ENV being that same environment? Or would that remove absolutely everything on your system? Can you remove base accidentally with this?
- [ ] --features - what is a feature?
- [ ] --no-pin - Does this ignore all pinned files? Just the one(s) pinned to the active environment?
- [ ] --use-index-cache - Don't know what channel index files are.
- [ ] Add more info to --dry-run
- [ ] Add more info to --yes
- [ ] Add more examples

**Comment by kathatherine** [comment]
For conda rename

- [ ] Not actually in release yet.
- [ ] Need consistency of period/no-period (this should also be throughout the CLI help - I vote yes on periods)
- [ ] Examples are missing new lines between them.

**Comment by ForgottenProgramme** [comment]
For **conda init**

- [ ] The `-d, --dry-run` argument does a dry run and displays what changes will be made when `conda init` is actually run. However the result displayed by `conda init -d` doesn't mention that "these are the changes that WILL take place". We can improve the user experience here by adding a line: "Following changes are expected on running `conda init` "

**Comment by ForgottenProgramme** [comment]
For **conda install**

- [ ] `--experimental-solver` not mentioned in the CLI help (probably because I'm using older conda version. Mentioning this here anyway.)

**Comment by kathatherine** [comment]
For conda run

- [ ] --dev needs a bit of rewriting - cwd should be spelled out there, even though it's also spelled out below.
- [ ] --debug-wrapper-scripts needs rewriting
- [ ] --cwd needs rewriting
- [ ] --no-capture-output, --live-stream needs a bit more info
- [ ] We should standardize where examples are placed on these pages, if possible. The examples for this command are at the top, while others are found at the bottom.

**Comment by kathatherine** [comment]
For conda search

- [ ] The main definition is bold. Why is that?
- [ ] Does the format for --subdir, --platform include the single quotes? Not completely clear.
- [ ] Tough problem for CLI help vs command reference in docs - the asterisks that surround scikit in the second example make it italicized without the asterisks visible in the docs
- [ ] Same problem with two examples without an extra newline between them makes them one long line in the docs (see third and sixth examples)

**Comment by kathatherine** [comment]
For conda update

- [ ] An example for package_spec would be nice
- [ ] --only-deps - only install dependencies as opposed to what? The named package(s)?
- [ ] --update-deps - doesn't this happen by default? Why does this need to be a flag?
- [ ] --satisfied-skip-solve - what are the "requested specs"? Where is "aggressive_update_packages" configured?
- [ ] --clobber - should added "(overwriting)" beside the word "clobbering" to make things more clear.
- [ ] --use-index-cache - Is there documentation on where a user's cache of channel index files exists?

**Comment by kathatherine** [comment]
For conda config

- [ ] The location of the .condarc file throughout this command doc needs changing/updating, with various OSes in mind. Mention --show-sources in the main definition, so the user can look up their own .condarc location(s).
- [ ] --validate - validates the config sources how?
- [ ] Fix the formatting of the Config Modifiers list to be consistent
- [ ] Several of these examples feel redundant - maybe rewrite them to be more explicit? Like the `conda config --describe` example could be `conda config --describe channel_priority` with an example text of "Print the description of the channel_priority configuration option to your command line. You can do this with any configuration option."

**Comment by kathatherine** [comment]
For common arguments between commands:

- [ ] --channel - "You can also use any name and the .condarc channel_alias value will be prepended." Any name? Also what prepends the .condarc channel_alias?
- [ ] The --channel flag description has a formatting error that is bolding the first line and putting the rest of the definition indented with no bolding. Likely a spacing issue.
- [ ]  --repodata-fn could use an example.
- [ ] --no-pin - Does this ignore all pinned files? Just the one(s) pinned to the active environment?
- [ ] --use-index-cache - Don't know what channel index files are.
- [ ] --use-index-cache - Is there documentation on where a user's cache of channel index files exists?
- [ ] --clobber - should added "(overwriting)" beside the word "clobbering" to make things more clear.
- [ ] –dev - Needs rewriting. Should either say “where we test a new conda source” or “where we test new conda sources”.
- [ ] Add more info to --dry-run
- [ ] Add more info to --yes
- [ ] Need consistency of period/no-period (this should also be throughout the CLI help - I vote yes on periods)
- [ ] Standardize example locations

**Comment by kathatherine** [comment]
There are some checkboxes still not checked as of now. The PR that's open related to this ticket (#11708) can be used for continuing work on cleaning this up as questions are properly answered. Or we can merge that PR and open up a new one (and/or create a new ticket) for the rest of it.

**Comment by LtDan33** [comment]
@kathatherine for the messages with checkboxes checked, does that mean that you've implemented/opened a PR with all those changes or that they have been merged?

**Comment by kathatherine** [comment]
@LtDan33 Said during our meeting, but adding for history: The checked checkboxes are either changes I have implemented in the connected PR or created a ticket for, which I noted near the checkbox line. Anything that isn't checked yet doesn't have a change in the PR or ticket as of yet.

**Comment by jmarshall** [comment]
For `conda create` and `conda install` see also #10491 — the user-facing documentation does not really explain what can appear in a `package_spec` on these command lines.

**Comment by kenodegard** [comment]
New tickets have been created, and #11708 is merged.
