### ISSUE TITLE
Missing tlz import during build

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#11698]
### What happened?

The canary builds are failing with a `tlz` import error. This is due to the build invoking `conda init --install`.

See https://github.com/conda/conda/runs/7731850991?check_suite_focus=true#step:3:761

### Tasks

- [x] https://github.com/conda/conda/pull/11699
- [x] https://github.com/conda/conda/pull/11700
- [x] https://github.com/conda-forge/conda-feedstock/pull/172
- [ ] https://github.com/AnacondaRecipes/conda-feedstock/pull/10
- [x] https://github.com/conda/conda-build/pull/4556
- [x] https://github.com/conda/conda/pull/11704
- [x] https://github.com/conda/conda/pull/11709

**Comment by jakirkham** [comment]
Perhaps we should install both `toolz` and `cytoolz`. Thought this was [already the case in conda-forge]( https://github.com/conda-forge/cytoolz-feedstock/blob/412878b301496fb3ee81989fa8e303f2b19909ab/recipe/meta.yaml#L30 ), but maybe we are missing something

**Comment by kenodegard** [comment]
[The canary builds are still failing](https://github.com/conda/conda/runs/7754554546?check_suite_focus=true#step:3:775)

After some digging it's all due to an innocent `path/to/python -m conda` call that should be `path/to/conda`, a short-term fix is proposed in https://github.com/conda/conda/pull/11709

**Comment by dholth** [comment]
Everything we use from toolz

- [ ] from toolz import 
- [ ] merge, 
- [ ] take, 
- [ ] interleave, 
- [ ] excepts, 
- [ ] merge_with, 
- [ ] concatv, 
- [ ] concat, 
- [ ] accumulate, 
- [ ] groupby, 
- [ ] unique
