### ISSUE TITLE
Drop pre-Python 3.7 codes

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#11718]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

Old Python code is less concise than newer code, let's get rid of unnecessary stuff.

### Linked Issues & PRs

- [ ] Replace `odict` with standard `dict` (since its now ordered by default)
- [ ] Replace `toolz.itertoolz.concatv` with arg unpacking
- [ ] Replace `toolz.itertoolz.concat` with `itertools.chain.from_iterable`
- [ ] Replace `toolz.itertoolz.groupby` with `itertools.groupby`

**Comment by dholth** [comment]
We ran pyupgrade https://github.com/conda/conda/pull/11909

**Comment by jakirkham** [comment]
Thanks Daniel! 🙏

Looks like some things (like replacing `odict` with `dict`) still remain

**Comment by kenodegard** [comment]
The code base is now solidly Python 3.7+ with dropping all `toolz`/`collections.OrderedDict` usage in favor of using stdlib functionality.

**Comment by dholth** [comment]
Amazing!
