### ISSUE TITLE
Yank older conda releases from PyPI

### ISSUE THREAD

**Issue by chenghlee** [conda/conda#11715]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Users who `pip install conda` can encounter issues (e.g., conda/conda#10246) caused by newer `conda` releases attempting to import modules from older, incompatible conda releases installed in their (per-user) site packages directories.

We have a [semi-documented resolution](https://github.com/conda/conda/issues/10246#issuecomment-701915353) for such problems. However, from a UX standpoint, I think we should yank the [older `conda` releases on PyPI](https://pypi.org/project/conda/#history) to prevent such issues from happening agin. We can later decide if/when to republish conda to PyPI (conda/conda#7472).

### Tasks

- [ ] Spike to investigate whether we can do this without side-effects (timebox = 1 day)
    - [ ] Is it safe to yank all these packages
    - [ ] Do we need to add a dummy package that says 'go here/install this instead'?
    - [ ] Can pip provide a pre/post install message

**Comment by chenghlee** [comment]
xref: conda/conda#11771

**Comment by rgommers** [comment]
This is a good idea.

> Is it safe to yank all these packages

Yes, this should be safe. users who have `pip install conda==4.3.16` or some such thing will still their exact version of `conda` installed after yanking. It's hard to imagine anyone still relying on `pip install conda` giving a now 6 year old `conda` version.

> Do we need to add a dummy package that says 'go here/install this instead'?

Yes, I would recommend doing that. If you make it an sdist-only package, you can print whatever message you like. See for example what PyTorch does (the PyPI package name is `torch`, and users frequently type `pytorch` instead): https://pypi.org/project/pytorch.

> Can pip provide a pre/post install message

Yes, via an sdist you have control over whatever message gets printed. Other than that, there is no separate "post-install message" feature for PyPI packages.

**Comment by chenghlee** [comment]
PyPI `conda` packages have been yanked: https://pypi.org/project/conda/#history
