### ISSUE TITLE
Multi-user installs

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#11731]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

Multi-user installs are confusing because our docs are lacking! We should help our users by defining a set of best-practices for these kinds of installs.

### Linked Issues & PRs

- [ ] https://github.com/conda/conda/issues/11687
- [ ] https://github.com/conda/conda/issues/11087

**Comment by hoedt** [comment]
Probably also related/relevant: #7227

**Comment by jaimergp** [comment]
xref, typical guidelines you might find in HPC documentation for their own users: https://docs.hpc.shef.ac.uk/en/latest/bessemer/software/apps/python.html#using-conda-python
