### ISSUE TITLE
Towards a non-experimental conda-libmamba-solver plugin

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#11756]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

This epic summarizes the work needed to release a new version of `conda-libmamba-solver` that can be considered non-experimental.

> I still need to create issues for some of the tasks. Coming soon :)

### Linked Issues & PRs

- [x] conda/conda#11639 
- [x] conda/conda#11875
- [x] https://github.com/conda-incubator/conda-libmamba-solver/pull/53
- [x] Discussion: adopting a fresh plugin API into a new released named 'stable' sounds like a big deal. Are we going to do RCs or canaries?
    - JL: Canaries  
- [X] Discussion: are we going to include conda-libmamba-solver in Miniconda? Miniforge? If so, when?
  - JL: Yes, after speaking with Cheng, at the earliest opportunity after 22.11.0
- [X] Discussion: promote `conda-incubator/conda-libmamba-solver` to `conda/conda-libmamba-solver`?
    - JL: Yes. https://github.com/conda-incubator/conda-libmamba-solver/issues/56
- [X] Documentation: docs.conda.io should include info about the solver. How should we contribute this? Through a parallel Sphinx site that gets embedded like we do with `conda-build`?
    - JL: Defer til unification of conda-* docs is decided. Content-wise, a "Getting started" guide plus another document covering the technical bits.
    - JRG: https://github.com/conda-incubator/conda-libmamba-solver/pull/58

### Reported bugs

- [x] conda/conda#11790
  - JRG: [This is the PR](https://github.com/conda-incubator/conda-libmamba-solver/pull/52) with the correct but behaviour breaking solution. [Alternative workaround for libmamba](https://github.com/mamba-org/mamba/issues/1924) raised too. 
- [x] conda/conda#11789
  - JRG: Not a bug, but an installation issue arising from a bloated `base` environment. The user provided a workaround. 
- [x] conda/conda#11750
- [ ] conda/conda-libmamba-solver#64
  - JRG: Not a bug strictly speaking, more like a temporary issue with the packaging landscape on Linux due to the openssl migration. Nothing we can do about it due to the nature of the backtracking algorithm of libsolv.

**Comment by Garra1980** [comment]
> hi all! am I correct that for 22.11 there is no possibility to use libmamba solver at all?

@jezdez @jaimergp can you pls clarify?

**Comment by jaimergp** [comment]
conda 22.11 will only work with conda-libmamba-solver 22.12 and above. Are you experiencing any issues updating, @Garra1980?

**Comment by Garra1980** [comment]
Ah, tried 22.12 and it worked, thanks @jaimergp!

**Comment by travishathaway** [comment]
Hi @jaimergp  and @jezdez,

I was wondering what the status of this epic is now that we have successfully release the new solver plugin and moved it out of "experimental". Are we ready to close this epic? 😁

I would suggest creating a new epic to track maintenance tasks for the now "officially supported" solver plugin.

Let me know what you think ✌️

**Comment by jaimergp** [comment]
I think we just need some announcements made and that's it. See https://github.com/conda/conda-libmamba-solver/issues/88#issue-1471210359

**Comment by jezdez** [comment]
I think we should close this epic, since we've shipped a version of the solver.
