### ISSUE TITLE
Create an index to manage plugins

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#11786]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

In order to help manage and keep the community approved list of plugins organized, we should create a machine readable index of these plugins somewhere (_to be determined_). We will then enable the conda CLI to add these plugins by discovering it there. Furthermore, this index can also be read by the future `conda.org` website and displayed/promoted there.

### Why is this needed?

To instill confidence in our user base and to help promote plugin authors. This index will also be used by the conda CLI itself and the conda.org website.

### What should happen?

Here are the primary tasks for this epic:

- [ ] Determine where we will store this index (technical)
- [ ] Determine how we will administer this index, including who will ultimately approve what goes there and how this process works (governance/admin)
- [ ] Add functionality to the conda CLI that will allow it to discover and install these plugins from the index (technical)

**Comment by jezdez** [comment]
FWIW, my thoughts following past discussions with @beeankha and @FFY00 are these:

### where to store index

- set up a `conda/plugins` repo as a community repo
- define an open contribution workflow that enables plugin authors to provide a metadata file per package containing plugin(s) using the usual GH PR review flow (if plugin authors don't provide one, the plugin won't show up, but it can still be installed)
- make the metadata file machine-readable
- the metadata contains fields like, name, version, repo URL, docs URL, compatible conda versions, license, used plugin hooks (used as category filter) etc

### maintenance

- set up a new conda governance team to review plugins contributions called "plugins"
- require review for PRs using GitHub's branch protection (or maybe even `CODEOWNERS`) by that team

### UI

- as part of the build-out of conda.org, add a "plugins" section (https://conda.org/plugins/) that pulls in the metadata during rendering and list the metadata provided by the contributor
- via a GitHub actions workflow, automatically create a compressed, single-file version of all plugin metadata and store it on S3
- create a `plugins` subcommand that fetches data from the S3 bucket to "search" the metadata
