### ISSUE TITLE
`conda env export` Epic

### ISSUE THREAD

**Issue by beeankha** [conda/conda#11800]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

Gathering together all of the `conda env export`-related issues that are open in the `conda` repo. The work requested in the tickets listed below might depend on / be related to the "[Collapse `conda_env` into `conda`](https://github.com/conda/conda/issues/11633)" and "[`environment.yaml` v2](https://github.com/conda/conda/issues/11341)" epics.

#### Issues and requests related to `--from-history`
- [ ] https://github.com/conda/conda/issues/9628 ([a PR has been submitted](https://github.com/conda/conda/pull/11532))
- [ ] https://github.com/conda/conda/issues/10345
- [ ] https://github.com/conda/conda/issues/11238

#### Path-related issues
- [ ] https://github.com/conda/conda/issues/10845
- [ ] https://github.com/conda/conda/issues/11575
- [ ] https://github.com/conda/conda/issues/11114

#### File-specific issues
- [ ] https://github.com/conda/conda/issues/10742
- [ ] https://github.com/conda/conda/issues/10636
- [ ] https://github.com/conda/conda/issues/10823
- [ ] https://github.com/conda/conda/issues/11102
- [ ] https://github.com/conda/conda/issues/10997

#### Miscellaneous `conda env export` issues
- [ ] https://github.com/conda/conda/issues/10320
- [ ] https://github.com/conda/conda/issues/11203
- [ ] https://github.com/conda/conda/issues/10587

**Comment by jeskowagner** [comment]
Hi Bianca,

Thanks for the collation! I submitted #9628 and wanted to mention that using this version, both #10345, #11238, and #11114 are fixed too. Hope we can get this merged in soon.

Best,
Jesko
