### ISSUE TITLE
Release v22.9.0

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#11802]
### Summary

Per [CEP 8](https://github.com/conda-incubator/ceps/blob/main/cep-8.md) it's time for another release of `conda`!

### Linked Issues & PRs

- [x] [Complete outstanding PRs](https://github.com/conda/conda/milestone/56)
- [x] Release PR: #11844 
    - [See release process](https://github.com/conda/conda/blob/main/RELEASE.md)
- [x] Published Release: https://github.com/conda/conda/releases/tag/untagged-22a6b499ff5d617fdf18
- [x] Create `22.9.x` branch
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/13
    - [x] Bump version https://github.com/AnacondaRecipes/conda-feedstock/pull/14
    - [x] Bump version https://github.com/conda-forge/conda-feedstock/pull/176
- [x] Handoff to packaging team
    - [x] Create a new issue in appropriate Slack channel
- [x] Announce release
    - [x] Slack
    - [x] Twitter
