### ISSUE TITLE
Content Trust CI/CD testing

### ISSUE THREAD

**Issue by awwad** [conda/conda#11804]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

- [ ] Add integration tests to conda that handle these:
  - [ ] (Note that some of these tests can be copied from the tests in conda-content-trust itself.)
  - [ ] verification of repodata and expected solves
    - [ ] include metadata with some artifacts in the solution set with signatures and some with none, and test that they are labeled appropriately in the transaction report in which the solution is displayed
    - [ ] multiple signatures for an artifact, first one bad and second one good  (should succeed with threshold==1)
    - [ ] threshold>1 verification for artifact signatures
  - [ ] regression with old (current) repodata
  - [ ] trust metadata: verification, discarding, warning:
    - [ ] good root update
      - [ ] including after a purge of $CONDAROOT .json files
    - [ ] bad root update
    - [ ] key_mgr updates
      - [ ] be sure to include key mgrs with multiple signatures and a threshold of 2 or more

### Linked Issues & PRs

- [ ] #
