### ISSUE TITLE
Add extra configuration parameters to channels in conda configuration

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#11825]
### What is the idea?

In order for to support authentication methods in a way that does not require us to either put a token or a username/password in the URL (e.g. anaconda.org token authentication method and basic HTTP authentication), we need a way to make the channel aware of which "fetch" backend to use. These backends will be implemented in the future by various fetch plugins.

How do we do that? We add a new configuration parameter called "channel_settings" that will hold additional setting for individual channels:

Here's what that looks like:

```yaml
channels:
  - defaults
  - https://package-corp.com
channel_settings:
  - channel: https://package-corp.com
    fetch: basic-auth
```

Using this method, we'll be able to switch out fetch backends on a per channel basis.

This method will allow us to attach arbitrary parameters to individual channels, so not only will the immediate use case for "fetch" be covered, but future use cases too.

### More background information

Relevant issues:

- #11600 
- #11696 

### Tasks

- [x] Update conda configuration so that it supports these extra configuration parameters for channels
- [x] Create a way for us to inspect this config. These extra parameters should show up when we run `conda config --show` and `conda config --get channels`
- [x] Add new tests to make sure that we can properly access these new parameters

**Comment by wolfv** [comment]
Interesting idea. I think there are already some other configuration ways to override some channel-specific settings, it might be interesting to consolidate them (`custom_channel` and `custom_multichannel`).

Also, in the mamba project we implement the same "rc"-file and we read the conda one, so it might be cool to properly specify what options you'll add and what additional uses you envision in the future.

In the powerloader PR we added a `mirrors` option that looks like so:

```
mirrors:
  conda-forge:
     - https://mymirror
     - oci://somemirror
     - ...
```

However, that could also be a key to the entry in this dictionary here.

**Comment by travishathaway** [comment]
Hi @wolfv,

I think that's a good idea. This could be the first step in simplifying conda's configuration.

As we move to adding more plugin hooks in conda, we want to keep these configurations fairly flexible because anticipating every future use case would be difficult. So, in that spirit it is kind of difficult to say exactly what will be there. Channel authentication is our immediate use case though.

We can say that a schema will be enforced, and the channel options will be simple key, value pairs at first (`str, str`). Would that suffice and allow you to predictably continue to parse these configuration files?

**Comment by travishathaway** [comment]
The issue description has been updated and is worth reading if you have been following along 👍
