### ISSUE TITLE
Plugins development: Phase two ✌️ 🔌 

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#11820]
## Summary

This epic outlines the development that will be undertaken during the second phase of development for plugins in `conda`. We hope that this successfully summarizes all efforts surrounding plugins and serves as a one-stop-shop for those wishing to know how we are progressing. Below, you will find epics related to our ongoing plugins work. These epics are primarily new plugin hooks we will be adding, new plugins themselves or other larger chunks of work related to plugins. Additionally, you will find a list of miscellaneous issues related to this phase of plugin work.

We also invite community members to use this epic as a place to discuss the ongoing work of plugins, especially if they are interested in getting involved with these ongoing development efforts.

## What are our goals?

In the [initial phase of plugin development](https://github.com/conda/conda/issues/11112), we set out to develop a prototype for how our plugin system could look like. During that phase, we added crucial components to conda such as the [pluggy](https://github.com/pytest-dev/pluggy) dependency and a hook to [add conda sub-commands as registered plugins](https://github.com/conda/conda/pull/11435). Also included in this development were the beginnings of a [separate repository that will hold example plugins](https://github.com/conda/conda-plugin-template). Although this initial work was a big step forward in accomplishing our ultimate goal of creating a plugin system, there is still a lot of work left to do to make this a fully featured system.

For the second phase of this work, we intend to accomplish the following goals:

- [x] Create several new hooks that will allow further overriding and customizing conda's behavior (e.g. hooks for HTTP requests and overriding the solver)
- [x] Add examples for how to use these hooks to our [examples repository](https://github.com/conda/conda-plugin-template)
- [x] Release a plugin for the libmamba solver (this will utilize our new solver hook)
- [ ] ~Release a plugin for overriding HTTP calls within conda~
- [x] Create lots of new documentation that will empower our community to begin writing their own plugins
- [x] Further refine our existing plugin hook for creating new conda sub-commands

## Plugin Epics 📚 

Here is a list of all the ongoing epics that are related to our high-level goals above.

- ~https://github.com/conda/conda/issues/11821~
- https://github.com/conda/conda/issues/11811
- https://github.com/conda/conda-libmamba-solver/issues/109
- https://github.com/conda/conda/issues/11826

### Administrative Tasks

- ~https://github.com/conda/conda/issues/11786~

## Plugin Issues 📄 

Here is a list of miscellaneous tasks related to completing this phase of development that were not large enough for their own epic.

### Documentation

- https://github.com/conda/conda/issues/12072

### New plugin example templates

- ~https://github.com/conda/conda-plugin-template/issues/9~
- ~https://github.com/conda/conda-plugin-template/issues/10~

### Refinements to existing plugin system

- https://github.com/conda/conda/issues/11777
- ~conda/conda#11823~
- https://github.com/conda/conda/issues/11860
- ~https://github.com/conda/conda/issues/12149~
- https://github.com/conda/conda/issues/12455
