### ISSUE TITLE
Use conda-package-handling 2.0 (to be released), add threadsafe extraction, remove libarchive dependency

### ISSUE THREAD

**Issue by dholth** [conda/conda#11858]
## Summary

`conda-package-streaming` (https://github.com/conda-incubator/conda-package-streaming) is a new library for efficiently handling conda packages, built while writing `conda-incubator/conda-index`. It is based on stdlib `zipfile` and `tarfile`, and the best zstd binding, https://github.com/indygreg/python-zstandard, which is available in defaults. It is notably threadsafe, and two times faster extracting `.conda` (before adding additional threads) compared to libarchive.

https://github.com/conda/conda-package-handling/pull/130 proposes a `conda-package-handling 2.0` that drops libarchive and depends on `conda-package-streaming`. `conda-package-handling` provides better support for creating conda packages, compared to `conda-package-streaming`. Most importantly it provides an exception-compatible wrapper for `extract()` so we can upgrade `conda` and `conda-build` without changing their code.

When this is complete conda will lose its special libarchive, and gain `conda-package-handling 2.0`, `conda-package-streaming`, and `zstandard` as dependencies.

For `conda-build`, `conda-package-handling 2.0` will put the `info-` component last in the archive. This shouldn't be a problem but will need to be tested. `conda-package-handling 2.0` also opens up the possibility of compressing `zstd` with threads, and converts `.tar.bz2` to `.conda` more efficiently.

## Linked Issues & PRs

- [x] https://github.com/conda/conda-package-handling/issues/133
- [x] release conda-package-streaming 0.4.0
- [x] add conda-package-streaming to defaults (at least conda channel)
- [x] update conda's own dependencies
- [x] check that this change doesn't make it more difficult to bootstrap new platforms
- [x] test
- [x] update dependencies for conda-build; test

**Comment by dholth** [comment]
As of January 2022 this is all in defaults and is working well.
