### ISSUE TITLE
Environment-specific configurations leak into new environments

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#11874]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

On my M1 Mac I often create environments for both `osx-arm64` (native) and `osx-64`, depending on the project and dependencies availabilities.

The way I create `osx-64` envs is by setting `CONDA_SUBDIR=osx-64 conda create ...` and then recording `subdir: osx-64` in the new environment's `.condarc`.

Today I found out a surprising (but reasonable) behaviour we might want to fix.

If I create a new environment from my osx-64 env, the subdir _leaks_ into the new environment configuration, which gets created with osx-64 architecture too:

```
$ CONDA_SUBDIR=osx-64 conda create -n env-osx-64 python
$ conda activate env-osx-64
$ conda config --env --set subdir osx-64
$ conda create -n env-osx-arm64 python
$ conda list -n env-osx-arm64
# shows osx-64 packages!
```

I am wondering if we should restrict certain keys from propagating to the creation of other environments. Or, in another words, based on the source of a certain key, choose whether we pick the env-specific config or the user/global one.

The logic would be something like:

```python
if target_environment != active_environment and config_origin(context.subdir) == os.path.join(active_environment, '.condarc'):
  context.subdir = user_context.subdir
```

`config_origin` and the different context objects do not exist, but you get the point.

### Conda Info

```shell
active environment : base
    active env location : /Users/jrodriguez/.local/anaconda
            shell level : 2
       user config file : /Users/jrodriguez/.condarc
 populated config files : /Users/jrodriguez/.local/anaconda/.condarc
                          /Users/jrodriguez/.condarc
          conda version : 4.13.0
    conda-build version : 3.21.9
         python version : 3.9.4.final.0
       virtual packages : __osx=11.2.3=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/jrodriguez/.local/anaconda  (writable)
      conda av data dir : /Users/jrodriguez/.local/anaconda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/jrodriguez/.local/anaconda/pkgs
                          /Users/jrodriguez/.conda/pkgs
       envs directories : /Users/jrodriguez/.local/anaconda/envs
                          /Users/jrodriguez/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.13.0 requests/2.28.1 CPython/3.9.4 Darwin/20.3.0 OSX/11.2.3 solver/libmamba conda-libmamba-solver/22.8.1 libmambapy/0.24.0
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /Users/jrodriguez/.local/anaconda/.condarc <==
channels:
  - conda-forge

==> /Users/jrodriguez/.condarc <==
add_pip_as_python_dependency: False
auto_update_conda: False
channel_priority: strict
channels:
  - conda-forge
show_channel_urls: True
experimental_solver: libmamba
```

### Conda list

<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at /Users/jrodriguez/.local/anaconda:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
anaconda-client           1.8.0              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
astroid                   2.8.5                    pypi_0    pypi
attrs                     22.1.0             pyh71513ae_1    conda-forge
babel                     2.10.3             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
black                     21.6b0                   pypi_0    pypi
blinker                   1.4                      pypi_0    pypi
brotlipy                  0.7.0           py39hb18efdd_1004    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.18.1               h3422bc3_0    conda-forge
ca-certificates           2022.6.15.2          h4653dfc_0    conda-forge
cachecontrol              0.12.11            pyhd8ed1ab_0    conda-forge
cachy                     0.3.0                      py_0    conda-forge
cctools                   973.0.1             h43ef6ec_10    conda-forge
cctools_osx-arm64         973.0.1             h8e51184_10    conda-forge
certifi                   2022.6.15.2        pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39h04d3946_0    conda-forge
chardet                   5.0.0            py39h2804cbe_0    conda-forge
charset-normalizer        2.0.7                    pypi_0    pypi
cleo                      0.8.1              pyhd8ed1ab_2    conda-forge
click                     8.1.3            py39h2804cbe_0    conda-forge
clikit                    0.6.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                    pypi_0    pypi
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
conda                     4.13.0           py39h2804cbe_1    conda-forge
conda-build               3.21.9           py39h2804cbe_1    conda-forge
conda-libmamba-solver     22.8.1             pyhd8ed1ab_0    conda-forge
conda-package-handling    1.8.1            py39hb18efdd_1    conda-forge
conda-tree                1.0.5              pyhd8ed1ab_0    conda-forge
crashtest                 0.3.1              pyhd8ed1ab_0    conda-forge
cryptography              37.0.4           py39h4cb6239_0    conda-forge
curl                      7.83.1               h2fcd78c_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
distlib                   0.3.5              pyhd8ed1ab_0    conda-forge
docutils                  0.19             py39h2804cbe_0    conda-forge
doit                      0.33.1                   pypi_0    pypi
expat                     2.4.8                h6b3803e_0    conda-forge
filelock                  3.8.0              pyhd8ed1ab_0    conda-forge
gettext                   0.19.8.1          h049c9fb_1008    conda-forge
git                       2.37.2          pl5321he503fb4_1    conda-forge
glob2                     0.7                        py_0    conda-forge
grayskull                 0.8.3                      py_0    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
icu                       70.1                 h6b3803e_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py39h2804cbe_0    conda-forge
ipython                   7.24.1           py39h32adebf_0    conda-forge
isort                     5.10.1                   pypi_0    pypi
jarowinkler               1.2.0            py39h6e3512e_0    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter_core              4.11.1           py39h2804cbe_0    conda-forge
keyring                   21.2.1           py39h2804cbe_3    conda-forge
krb5                      1.19.3               hf9b2bbe_0    conda-forge
lazy-object-proxy         1.6.0                    pypi_0    pypi
ld64                      609                 h954701c_10    conda-forge
ld64_osx-arm64            609                 h6ce2ded_10    conda-forge
libarchive                3.5.2                h69ec738_3    conda-forge
libblas                   3.9.0           15_osxarm64_openblas    conda-forge
libcblas                  3.9.0           15_osxarm64_openblas    conda-forge
libcurl                   7.83.1               h2fcd78c_0    conda-forge
libcxx                    14.0.6               h04bba0f_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0.dev0      11_0_1_hf114ba7_23    conda-forge
libgfortran5              11.0.1.dev0         hf114ba7_23    conda-forge
libiconv                  1.16                 h642e427_0    conda-forge
liblapack                 3.9.0           15_osxarm64_openblas    conda-forge
liblief                   0.12.1               h2e04ded_0    conda-forge
libllvm13                 13.0.1               hfd59cb2_2    conda-forge
libmamba                  0.24.0               h1c735bf_1    conda-forge
libmambapy                0.24.0           py39h5b36d7b_1    conda-forge
libnghttp2                1.47.0               h232270b_1    conda-forge
libopenblas               0.3.20          openmp_h2209c59_0    conda-forge
libsolv                   0.7.22               h1280f1d_0    conda-forge
libsqlite                 3.39.2               h2c9beb0_1    conda-forge
libssh2                   1.10.0               hb80f160_3    conda-forge
libxml2                   2.9.14               h9d8dfc2_4    conda-forge
libzlib                   1.2.12               ha287fd2_2    conda-forge
linkify-it-py             1.0.1                    pypi_0    pypi
livereload                2.6.3                    pypi_0    pypi
llvm-openmp               14.0.4               hd125106_0    conda-forge
lockfile                  0.12.2                     py_1    conda-forge
lxml                      4.6.3                    pypi_0    pypi
lz4-c                     1.9.3                hbdafb3b_1    conda-forge
lzo                       2.10              h642e427_1000    conda-forge
macfsevents               0.8.1                    pypi_0    pypi
mako                      1.1.4                    pypi_0    pypi
mamba                     0.24.0           py39hde45b87_1    conda-forge
markdown                  3.3.4                    pypi_0    pypi
markdown-it-py            1.1.0                    pypi_0    pypi
markupsafe                2.1.1            py39hb18efdd_1    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mccabe                    0.6.1                    pypi_0    pypi
mdit-py-plugins           0.2.8                    pypi_0    pypi
msgpack-python            1.0.4            py39hab5e169_0    conda-forge
mypy_extensions           0.4.3            py39h2804cbe_5    conda-forge
myst-parser               0.15.2                   pypi_0    pypi
natsort                   7.1.1                    pypi_0    pypi
nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
networkx                  2.8.6              pyhd8ed1ab_0    conda-forge
nikola                    8.1.3                    pypi_0    pypi
numpy                     1.23.1           py39h7df2422_0    conda-forge
openssl                   1.1.1q               ha287fd2_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pastel                    0.2.1              pyhd8ed1ab_0    conda-forge
patch                     2.7.6             h27ca646_1002    conda-forge
pathspec                  0.8.1                    pypi_0    pypi
pcre2                     10.37                hcf5f1cc_1    conda-forge
perl                      5.32.1          2_h9b22ae9_perl5    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
piexif                    1.1.3                    pypi_0    pypi
pillow                    8.3.2                    pypi_0    pypi
pip                       21.1.2             pyhd8ed1ab_0    conda-forge
pkginfo                   1.8.3              pyhd8ed1ab_0    conda-forge
platformdirs              2.4.0                    pypi_0    pypi
poetry                    1.1.7            py39h2804cbe_0    conda-forge
poetry-core               1.0.8            py39h2804cbe_1    conda-forge
progressbar2              4.0.0              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
psutil                    5.9.1            py39h9eb174b_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py-lief                   0.12.1           py39h3c22d25_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.3           py39hb18efdd_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pylev                     1.4.0              pyhd8ed1ab_0    conda-forge
pylint                    2.11.1                   pypi_0    pypi
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyhd8ed1ab_1    conda-forge
pyrsistent                0.14.11          py39h46acfd9_2    conda-forge
pyrss2gen                 1.1                      pypi_0    pypi
pysocks                   1.7.1            py39h2804cbe_5    conda-forge
python                    3.9.4           h5b20da3_0_cpython    conda-forge
python-dateutil           2.8.1                    pypi_0    pypi
python-fastjsonschema     2.16.1             pyhd8ed1ab_0    conda-forge
python-libarchive-c       4.0              py39h2804cbe_1    conda-forge
python-utils              3.3.3              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.2.1           pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39hb18efdd_4    conda-forge
rapidfuzz                 2.2.0            py39h6e3512e_0    conda-forge
readline                  8.1.2                h46ed386_0    conda-forge
regex                     2021.4.4                 pypi_0    pypi
reproc                    14.2.3               h3422bc3_0    conda-forge
reproc-cpp                14.2.3               hbdafb3b_0    conda-forge
requests                  2.26.0                   pypi_0    pypi
requests-toolbelt         0.9.1                      py_0    conda-forge
ripgrep                   13.0.0               h65448a5_2    conda-forge
ruamel-yaml               0.17.16                  pypi_0    pypi
ruamel.yaml               0.17.21          py39hb18efdd_1    conda-forge
ruamel.yaml.clib          0.2.6            py39hb18efdd_1    conda-forge
ruamel.yaml.jinja2        0.2.4                      py_1    conda-forge
ruamel_yaml               0.15.80         py39h9eb174b_1007    conda-forge
setuptools                65.3.0             pyhd8ed1ab_1    conda-forge
shellingham               1.5.0              pyhd8ed1ab_0    conda-forge
shyaml                    0.6.2              pyhd3deb0d_0    conda-forge
sigtool                   0.1.3                h7747421_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sphinx                    4.2.0                    pypi_0    pypi
sphinx-argparse           0.3.1                    pypi_0    pypi
sphinx-autobuild          2021.3.14                pypi_0    pypi
sphinx-rtd-theme          1.0.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-plantuml    0.21                     pypi_0    pypi
sphinxcontrib-programoutput 0.17                     pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
sqlite                    3.39.2               h40dfcc0_1    conda-forge
stdlib-list               0.7.0                      py_2    conda-forge
tapi                      1100.0.11            he4954df_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.11.4             pyha770c72_0    conda-forge
tornado                   6.1                      pypi_0    pypi
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
typed-ast                 1.5.4            py39h9eb174b_0    conda-forge
typing                    3.10.0.0           pyhd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
uc-micro-py               1.0.1                    pypi_0    pypi
unidecode                 1.2.0                    pypi_0    pypi
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
virtualenv                20.16.3          py39h2804cbe_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
wrapt                     1.13.3                   pypi_0    pypi
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
yaml-cpp                  0.7.0                h9a09cb3_1    conda-forge
yapsy                     1.12.2                   pypi_0    pypi
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               ha287fd2_2    conda-forge
zstd                      1.5.2                h8128057_4    conda-forge
```
</details>

### Tasks

- [ ] Spike to investigate what other configurations have side-effects when set on the env level. (timebox = 1 day).
- [ ] Update this task list with documentation changes and/or recommendations to change this issue.

**Comment by chenghlee** [comment]
> I am wondering if we should restrict certain keys from propagating to the creation of other environments.

Yes! And speaking someone who regularly switches between Anaconda's and conda-forge's repositories depending on environments & use case, I would also suggest that any channel-related configuration settings should be in the "do not propagate to other environments" list; this would include options like `channels`, `channel_alias`, and `default_channels` (in addition to `subdir`).
