### ISSUE TITLE
Various speed improvements to conda

### ISSUE THREAD

**Issue by dholth** [conda/conda#11895]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

- [ ] Release, use conda-package-handling 2.0 #11858 
* efficient `.conda` handling extracts twice as fast as existing implementation
* threadsafe extraction doubles `.tar.bz2` handling and speeds up conda by 20%
- [ ] Parallel package dowloads, potential for 3x speed improvement depending on latency/bandwidth #11841 
- [ ] Parallel extraction (implement as enabled by conda-package-handling upgrade), also #11841
- [ ] Incremental repodata (6000x bandwidth savings on `repodata.json` updates) #11640 

This should be a nice collection of improvements.

### Linked Issues & PRs

- [ ] #11858
- [ ] #11841 
- [ ] #11640

**Comment by dholth** [comment]
- [ ] solver

**Comment by dholth** [comment]
https://dholth.github.io/conda-benchmarks/#conda_install.TimeInstall.time_explicit_install?conda-package-handling=1.9.0&conda-package-handling=2.0.0a2&p-latency=0.0 is a graph showing the conda-package-handling improvements when installing these packages https://github.com/dholth/conda-benchmarks/blob/main/conda-osx-64.lock

Drops from 3.3 to 1.3 seconds. On this laptop it saves about 2 seconds in all cases, but when the downloads take longer the conda-package-handling speedup is a lesser percentage of the whole operation.

**Comment by dholth** [comment]
Closing with the completion of #11640
