### ISSUE TITLE
Release 22.11.X

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#11932]
### Summary

Placeholder for `conda 22.11.x` release(s).

### Tasks

[milestone]: https://github.com/conda/conda/milestone/57
[doc]: https://github.com/conda/conda/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda/releases
[main]: https://github.com/AnacondaRecipes/conda-feedstock
[conda-forge]: https://github.com/conda-forge/conda-feedstock

<details>
<summary>22.11.0</summary>

- [x] [Complete outstanding PRs][milestone]
- [x] Create release PR (#12127)
    - See [release process][doc]
- [x] [Publish Release][releases]: https://github.com/conda/conda/releases/tag/22.11.0
- [x] Create/update `22.11.X` branch
- [x] Feedstocks
    - [x] Bump version [Anaconda's main][main]: https://github.com/AnacondaRecipes/conda-feedstock/pull/17
    - [x] Bump version [conda-forge][conda-forge]: https://github.com/conda-forge/conda-feedstock/pull/181
      - [x] Remove [this patch](https://github.com/conda-forge/conda-feedstock/blob/main/recipe/gh9946_utf_16_replacement.patch) from the conda-forge conda feedstock 
- [x] Hand off to the Anaconda packaging team

</details>

- [x] Create release PR (#12152)
    - See [release process][doc]
- [x] [Publish Release][releases]: https://github.com/conda/conda/releases/tag/22.11.1
- [x] Create/update `22.11.X` branch
- [x] Feedstocks
    - [x] Bump version [Anaconda's main][main]: https://github.com/AnacondaRecipes/conda-feedstock/pull/19
    - [x] Bump version [conda-forge][conda-forge]: https://github.com/conda-forge/conda-feedstock/pull/192
- [x] Hand off to the Anaconda packaging team
- [x] Announce release
    - [x] Slack: https://conda.slack.com/archives/C017F7C0VM3/p1670452206016979
    - [x] Twitter: https://twitter.com/condaproject/status/1600626457948016642?s=20&t=kYnZAEjQrsBAquxHITJE0w
    - [x] Discourse: https://conda.discourse.group/t/conda-22-11-1-release/139
    - [x] Gitter: https://gitter.im/conda/conda?at=639113f13daaa326ba7421c3
    - [x] Element: https://matrix.to/#/!SgckMCYyQUhdyooKZe:gitter.im/$MvPi0tN4RcAnu2ZASLaaRo_QmRMnyLbZQfnZZYZTBYo?via=gitter.im&via=matrix.org

**Comment by johnnynunez** [comment]
Yeah! Python 3.11 support please. It should be the default.
Python 3.11 is between 10-60% faster than Python 3.10. On average, we measured a 1.25x speedup on the standard benchmark suite. See Faster CPython for details.
https://docs.python.org/3.11/whatsnew/3.11.html
https://www.phoronix.com/news/Python-3.11-Released

**Comment by johnnynunez** [comment]
Benchmark https://www.phoronix.com/review/python-311-performance

**Comment by johnnynunez** [comment]
pytorch support python 3.11

**Comment by jezdez** [comment]
Closing this for now since I believe the dust has settled about the release. If needed we can reopen this.
