### ISSUE TITLE
MatchSpec: should `=` be valid?

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#12046]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

> Should we add this test case?
> 
> ```
> with pytest.raises(InvalidVersionSpec):
>     VersionSpec("=")
> ```
> 
> If `==` is invalid, then `=` (single equals) should be as well.

_Originally posted by @chenghlee in https://github.com/conda/conda/pull/12014#discussion_r1008285408_
      

### Tasks

- [ ] 🔍 spike: determine if `=` should be valid or not
- [ ] implement necessary changes
- [ ] update tests
