### ISSUE TITLE
Canary builds are broken

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#12047]
### What happened?

Canary builds broke with the plugin PR #11960 when we added the pluggy dependency.

This is a revival of the same issue we encountered when we attempted to deprecated the vendored toolz.

Xref https://github.com/conda/conda-build/issues/4561 https://github.com/conda/conda-build/issues/4572 https://github.com/conda/conda-build/pull/4604

### Tasks

- [x] Fix root cause: https://github.com/conda/conda-build/pull/4604
- [x] Test conda-build canary version to ensure the issue is resolved
- [x] Release conda-build
- [x] https://github.com/conda/conda/pull/12115

**Comment by kenodegard** [comment]
Cleaned up canary workflow:
- https://github.com/conda/conda/pull/12040
- https://github.com/conda/conda-build/pull/4608

**Comment by kenodegard** [comment]
Conda canaries are back online
