### ISSUE TITLE
CI tests for pull requests should run when they need to (i.e. not everytime a commit is pushed)

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#12133]
### What is the idea?

I recently observed for the following pull requests:

- https://github.com/conda/conda/pull/12132

That all the tests were running in CI even though we were only editing the README file. This should not happen.

### Why is this needed?

To decrease load from test runners and to only use these resources when necessary (i.e. eco-friendly tests 😉 🌲 ).

### What should happen?

We need to add more complex rules to our GitHub action that preferably only run tests when files concerned with the software itself have been changed.

Excluded from this include but are not limited to the following:

- READMEs and other top level documentation (e.g. CONTRIBUTING too)
- Documentation; when this changes we should only run the applicable CI tests which is the documentation building/staging tool.
- Others?

### Tasks

- [x] Come up with a more reasonable way to configure GitHub actions to only run tests when necessary
  - [x] https://github.com/conda/conda/pull/12141
  - [x] https://github.com/conda/conda/pull/12147
- [x] Figure out what else needs to be excluded, if anything
- [x] Update branch protections' required checks to specify the "Tests / Analyze results" instead of individual jobs
- [x] Test this manually and partner up with a reviewer early to explain how your new changes work (this will be counted as part of the review process).
  - [x] https://github.com/conda/conda/pull/12144 **Test succeeded!**
  - [x] https://github.com/conda/conda/pull/12145
  - [x] https://github.com/conda/conda/pull/12146
- [x] Port this over to conda-build
  - [x] https://github.com/conda/conda-build/pull/4664
- [x] Use a GitHub Action instead to determine whether tests are being skipped
  - [x] https://github.com/conda/conda/pull/12180
  - [x] https://github.com/conda/conda-build/pull/4675

**Comment by dholth** [comment]
https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#using-filters-to-target-specific-paths-for-pull-request-or-push-events

**Comment by kenodegard** [comment]
Just created 3 PRs to test the three possible conditions of only non-code changes (#12144), only code changes (#12145), and mixed changes (#12146). The workflows are being triggered correctly so this looks to be a successful change!

**Comment by kenodegard** [comment]
This appears resolved with #12180 and conda/conda-build#4675
