### ISSUE TITLE
Release 23.1.X

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#12224]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

Placeholder for `conda 23.1.0` release. See [CEP8](https://github.com/conda-incubator/ceps/blob/main/cep-8.md).

| Roles | Person |
|---|---|
| Pilot | @kenodegard |
| Co-pilot | @jezdez |
| Jumpseat | @beeankha |

### Linked Issues & PRs

[matrix]: https://matrix.to/#/#conda-release:matrix.org
[milestone]: https://github.com/conda/conda/milestone/58
[releases]: https://github.com/conda/conda/releases
[main]: https://github.com/AnacondaRecipes/conda-feedstock
[conda-forge]: https://github.com/conda-forge/conda-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda/

- [x] Add release participants to [#conda-release:matrix.org][matrix]
- [x] Release planning meeting to discuss obstacles or concerns
    - Scheduled for 2023/1/8
    - <details><summary>Notes</summary>

      - #12161
      - #11795
      - #11825
      - @mbargull found an issue with the notifications feature and Python upgrades, he will briefly investigate and report back (edit: this turned out to be a non-issue)
      - miniconda release is not part of this process, perhaps in March release
      - continue experimenting with pilot/co-pilot release managers, reevaluate post-release
      - limited marketing this time around since its a limited release

      </details>
- [x] [Complete outstanding PRs][milestone]
- [x] Create release PR (https://github.com/conda/conda/pull/12249)
    - See release process https://github.com/conda/conda/blob/main/RELEASE.md
- [x] [Publish Release][releases] (https://github.com/conda/conda/releases/tag/23.1.0)
- [x] Create/update `YY.M.x` branch
- [x] Activate the `YY.M.x` branch as a version on [Read The Docs][ReadTheDocs]
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/23
    - [x] https://github.com/conda-forge/conda-feedstock/pull/197
    - [x] https://github.com/conda-forge/conda-feedstock/pull/200
    - Link any other feedstock PRs that are necessary
- [x] Hand off to the Anaconda packaging team
- [x] Announce release
    - [x] [Drafts](https://github.com/conda/communications/pull/4)
    - [x] [Discourse](https://conda.discourse.group/t/conda-23-1-0-release/208)
    - [x] Twitter (scheduled for 2023-02-27)
    - [x] [Matrix](https://matrix.to/#/!SgckMCYyQUhdyooKZe:gitter.im/$IT46oxnsMnMo5vMfI__DlrdLFuXbeCjYgUVf0Juh9zw?via=gitter.im&via=matrix.org&via=tum.de)

**Comment by johnnynunez** [comment]
Python 3.11 is out in anaconda https://github.com/ContinuumIO/anaconda-issues/issues/13082

**Comment by kenodegard** [comment]
@johnnynunez Python 3.11 support will be in the March release (23.3.0)

**Comment by johnnynunez** [comment]
@kenodegard could you guys build packages for python 3.11? https://github.com/pytorch/vision/pull/7108

**Comment by LtDan33** [comment]
@johnnynunez for requests for specific packages you can direct that [here](https://github.com/ContinuumIO/anaconda-issues/issues/new/choose) by opening "Package build request". That way this issue can focus on the release. Thanks!

(In general, Anaconda will definitely be building packages with 3.11 support in the future)

**Comment by billti** [comment]
I have an docker script which installs via curl from <http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh> which is still fetching 22.11.1. I see the docs at <https://docs.conda.io/en/latest/miniconda.html#linux-installers> also still point to 22.11.1.

Our scanning tool is flagging some packages in that version for vulnerabilities, which hopefully 23.1.0 will fix. Any idea when the installers/docs will point to this release by default? Thanks.

**Comment by kenodegard** [comment]
@billti the installers are released at a different cadence than conda itself, and unfortunately we don't control that process, we will probably see an updated installer in the next few months, sorry for not being able to provide anything more concrete

**Comment by kenodegard** [comment]
Conda 23.1.0 was released to defaults on Jan 24th and to conda-forge earlier today so we are considering this release completed
