### ISSUE TITLE
Support `pathlib`

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#12281]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

`pathlib` is nice and makes things cleaner, need to adjust `conda` to natively handle `pathlib`.

### Linked Issues & PRs

- [ ] Update `conda.gateways.disk.delete.rm_rf`

**Comment by jezdez** [comment]
@kenodegard I think this is done?

**Comment by kenodegard** [comment]
Not really, we've just been gradually adding `pathlib` support. No dedicated effort to make a plan and executing on it.
