### ISSUE TITLE
23.3 Deprecations/23.9 Removals

### ISSUE THREAD

**Issue by beeankha** [conda/conda#12391]
### Summary

Track features that are part of the conda 23.9 deprecations and eventual 24.3 removals

```[tasklist]
# Deprecations
- [ ] [`conda/lock.py`](https://github.com/conda/conda/blob/28eb9aec0dd783f66420983d09514c7588d83269/conda/lock.py) (see #11571)
- [ ] [`conda/_vendor/toolz/__init__.py`](https://github.com/conda/conda/blob/28eb9aec0dd783f66420983d09514c7588d83269/conda/_vendor/toolz/__init__.py) (see #12125)
- [ ] [`conda/_vendor/tqdm/__init__.py`](https://github.com/conda/conda/blob/28eb9aec0dd783f66420983d09514c7588d83269/conda/_vendor/tqdm/__init__.py) (see #12125)
- [ ] https://github.com/conda/conda/issues/12388
- [ ] https://github.com/conda/conda/issues/12387
- [ ] https://github.com/conda/conda/issues/12386
- [ ] https://github.com/conda/conda/issues/12385
- [ ] https://github.com/conda/conda/issues/12384
- [ ] https://github.com/conda/conda/issues/12383
- [ ] https://github.com/conda/conda/issues/12382
- [ ] https://github.com/conda/conda/issues/12381
- [ ] https://github.com/conda/conda/issues/12380
- [ ] https://github.com/conda/conda/issues/12379
```

**Comment by beeankha** [comment]
Also connecting a separate module deprecation issue, since this one needs some investigation and a possible refactor:
- https://github.com/conda/conda/issues/12421
