### ISSUE TITLE
Release 23.3.0

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#12458]
### Summary

Placeholder for `conda 23.3.0` release.

| Pilot | @kenodegard |
|---|---|
| Co-Pilot | @beeankha |

### Linked Issues & PRs

[conda-build]: https://github.com/conda/conda-build/issues/4795
[milestone]: https://github.com/conda/conda/milestone/59
[process]: https://github.com/conda/conda/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda/releases
[main]: https://github.com/AnacondaRecipes/conda-feedstock
[conda-forge]: https://github.com/conda-forge/conda-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda/

- [x] [Release `conda-build 3.24.0`][conda-build]
- [x] [Complete outstanding PRs][milestone]
- [x] Create release PR
    - https://github.com/conda/conda/pull/12486
    - See [release process][process]
- [x] [Publish Release][releases]
    - https://github.com/conda/conda/releases/tag/23.3.0
- [x] Create/update `23.3.x` branch
    - https://github.com/conda/conda/tree/23.3.x
- [x] Activate the `23.3.x` branch as a version on [Read The Docs][ReadTheDocs]
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/25
    - [x] https://github.com/conda-forge/conda-feedstock/pull/202
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/26
    - [x] https://github.com/conda-forge/conda-feedstock/pull/205
- [x] Hand off to the Anaconda packaging team
- [x] Announce release
    - [x] https://github.com/conda/communications/pull/12
    - [x] [Discourse](https://conda.discourse.group/t/conda-23-3-1-conda-build-3-24-0-releases/241)
    - [x] [Twitter](https://twitter.com/condaproject/status/1641739612430434304?s=20)
    - [x] [Matrix](https://matrix.to/#/!SgckMCYyQUhdyooKZe:gitter.im/$15xAmOvqMImZOn1EymcXOXiyaY39mxf_qmAEKGG7MfE?via=gitter.im&via=matrix.org&via=cadair.com)

**Comment by dholth** [comment]
- [ ] https://github.com/conda/conda/pull/12513 Regression
