### ISSUE TITLE
Add plugin hook for shell interfaces

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#12451]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

Shell interfaces are difficult to support as they differ widely, and the conda development team has limited experience with these exotic shells to offer meaningful support.

Let's rely on the plugin infrastructure to allow plugins that extend the supported shell interfaces. This means that most of the shells supported out of the box today will be moved into standalone plugins, and we will request community support for future development efforts.

### Linked Issues & PRs

- [ ] https://github.com/conda/conda/issues/12406
- [ ] https://github.com/conda/conda/issues/11116
- [ ] Convert fish support into a plugin
- [ ] Convert xonsh support into a plugin
- [ ] Convert tcsh/csh support into a plugin

**Comment by NewtonChutney** [comment]
Hello @kenodegard, any update on plugins?
A tentative date of release?
