### ISSUE TITLE
`conda config` Improvements

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#12463]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

An aggregation of all issues/PRs related to `conda config`.

Many of these issues can be considered low-severity bugs since its always possible to manually edit the `.condarc` files.

### Linked Issues & PRs

- [ ] https://github.com/conda/conda/issues/12403
- [ ] https://github.com/conda/conda/issues/12356
- [ ] https://github.com/conda/conda/issues/12295
- [ ] https://github.com/conda/conda/issues/12137
- [ ] https://github.com/conda/conda/issues/12136
- [ ] https://github.com/conda/conda/issues/11874
- [ ] https://github.com/conda/conda/issues/12122
- [ ] https://github.com/conda/conda/issues/11377
- [ ] https://github.com/conda/conda/issues/11006
- [ ] https://github.com/conda/conda/issues/10821
- [ ] https://github.com/conda/conda/pull/11627

**Comment by jaimergp** [comment]
xref #12355
