### ISSUE TITLE
Support for `pyproject.toml`

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#12462]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

`pyproject.toml` and build systems are all the rage in the Python world today. conda needs to figure out how it fits into this world.

### Linked Issues & PRs

- [ ] https://github.com/conda/conda/issues/10633
- [ ] https://github.com/conda/conda/issues/12126
- [ ] https://github.com/conda/conda-build/issues/4774
- [ ] https://github.com/conda/conda-build/issues/4002
- [ ] https://github.com/conda/conda-build/issues/3919
- [ ] https://github.com/conda/conda-build/issues/3563

**Comment by wvreeven** [comment]
Is there any update on this? I see that is has been removed from the planning. Does this mean that this will not be implemented? Any information would be very welcome.

**Comment by kenodegard** [comment]
@wvreeven no progress on this yet

The move from the Planning board to Epics was just us reorganizing tickets (and GitHub being surprisingly noisy about it), no deeper meaning.

**Comment by xuanswe** [comment]
Hi, do you have an idea about the time when this feature could be done?

**Comment by shifenhutu** [comment]
i use https://github.com/astral-sh/uv now, it's better
