### ISSUE TITLE
Release 23.3.1

### ISSUE THREAD

**Issue by dholth** [conda/conda#12548]
### Summary

Placeholder for `conda 23.3.1` release.

| Pilot | @kenodegard |
|---|---|
| Co-Pilot | @beeankha |

### Tasks

[milestone]: https://github.com/conda/conda/milestone/56
[process]: https://github.com/conda/conda/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda/releases
[main]: https://github.com/AnacondaRecipes/conda-feedstock
[conda-forge]: https://github.com/conda-forge/conda-feedstock

- [x] [Complete outstanding PRs][milestone]
- [x] Create release PR
    - https://github.com/conda/conda/pull/12547
    - See [release process][process]
- [ ] [Publish Release][releases]
- [ ] Update `23.3.x` branch
- [x] Activate the 23.3.x branch as a version on [Read The Docs](https://readthedocs.com/projects/continuumio-conda/)
- [ ] Feedstocks
    - [ ] Bump version [Anaconda's main][main]
    - [ ] Bump version [conda-forge][conda-forge]
    - Link any other feedstock PRs that are necessary
- [x] #12546 
- [ ] Hand off to the Anaconda packaging team
- [ ] Announce release
    - [ ] Slack
    - [ ] Twitter
