### ISSUE TITLE
Generic Plugin Hooks

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#12595]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

This epic exists to document and plan our efforts for implementing the following CEP proposal: https://github.com/conda-incubator/ceps/pull/45

Although it hasn't been pasted, we still feel appropriate to begin developing prototypes.

### Linked Issues & PRs

- [ ] https://github.com/conda/conda/issues/12593
- [ ] https://github.com/conda/conda/issues/12594
- [ ] Add an example to the [conda-plugin-template](https://github.com/conda/conda-plugin-template) repository _issue will be created later_

**Comment by travishathaway** [comment]
This work will be released in the `23.7.0` version 🚀

**Comment by jezdez** [comment]
@travishathaway Do you think it would be worth announcing these hooks in a small blog post on conda.org?

**Comment by travishathaway** [comment]
@jezdez, yes I think that's a good idea.

I can add another issue for it and link it here.
