### ISSUE TITLE
Ensure that the docstrings for the project are descriptive and up to date

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#12613]
### What is the idea?

As we continue to open up conda with various plugin hooks, we would like to make sure that the code is easily read.

```[tasklist]
- [ ] https://github.com/conda/conda/pull/12620
- [ ] https://github.com/conda/conda/issues/12668
- [ ] Review all public class docstrings (see D101)
- [ ] Review all public method docstrings (see D102)
- [ ] Review all public function docstrings (see D103)
- [ ] Review all public package docstrings (see D104)
- [ ] Review all magic method docstrings (see D105)
- [ ] Review all public nested class docstrings (see D106)
- [ ] Review all `__init__` docstrings (see D107)
- [ ] Review nested `README.md`s (e.g. `conda/core/README.md`) and consider removing/combining into `__init__.py` docstrings
```
