### ISSUE TITLE
Release 23.5.x

### ISSUE THREAD

**Issue by beeankha** [conda/conda#12625]
### Summary

Placeholder for `conda 23.5.0` release.

| Pilot | @beeankha  |
|---|---|
| Co-pilot | @kenodegard  |

### Tasks

<details>
<summary><b>The week before release week</b></summary>

- [x] Create [release branch (named `23.5.x`)](https://github.com/conda/conda/tree/23.5.x)
- [x] Ensure release candidates are being successfully built (see `conda-canary/label/23.5.x`)
- [x] [Complete outstanding milestone items](https://github.com/conda/conda/milestone/60)
- [x] #12663 
     

</details>

<details>
<summary><b>Release week</b></summary>

- [x] Create release PR (see [release process](https://github.com/conda/conda-build/blob/main/RELEASE.md)) https://github.com/conda/conda/pull/12685
- [x] [Publish release](https://github.com/conda/conda/releases/tag/23.5.0)
- [x] https://github.com/conda/conda/pull/12702
- [x] Activate the `23.5.x` branch on [ReadTheDocs](https://readthedocs.com/projects/continuumio-conda/)
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/29
    - [x] https://github.com/conda-forge/conda-feedstock/pull/207
    - [x] https://github.com/conda-forge/conda-feedstock/pull/208
    - [x] https://github.com/conda-forge/conda-feedstock/pull/209
- [x] Hand off to the Anaconda packaging team
- [x] Announce release
    - Blog post
        - [x] https://github.com/conda-incubator/conda-dot-org/pull/139
    - Long form
        - [x] https://github.com/conda/communications/pull/16
        - [x] [Discourse](https://conda.discourse.group/t/conda-23-5-0-conda-build-3-25-0-and-conda-libmamba-solver-23-5-0-releases/285)
        - [x] [Matrix (conda/conda)](https://matrix.to/#/!SgckMCYyQUhdyooKZe:gitter.im/$QV6nzyiVJ1a15yuIK-rEI1Cfaxs_VuljHTVybaqJUyM?via=gitter.im&via=matrix.org&via=t2bot.io) (this auto posts from Discourse)
    - Summary
        - [x] [Twitter](https://twitter.com/condaproject/status/1662135231481085954)
        - [x] Matrix (conda/conda-release)

</details>

</details>

<details>
<summary><b>Hotfix 23.5.1</b></summary>

- [x] https://github.com/conda/conda/pull/12874
- [x] Create release PR (see [release process](https://github.com/conda/conda-build/blob/main/RELEASE.md)) https://github.com/conda/conda/pull/12875
- [x] Publish release https://github.com/conda/conda/releases/tag/23.5.1
- [ ] https://github.com/conda/conda/pull/12878
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/31
    - [ ] https://github.com/conda-forge/conda-feedstock/pull/211
- [x] Hand off to the Anaconda packaging team

</details>

<details>
<summary><b>Hotfix 23.5.2</b></summary>

- [x] https://github.com/conda/conda/pull/12880
- [x] Create release PR (see [release process](https://github.com/conda/conda-build/blob/main/RELEASE.md)) https://github.com/conda/conda/pull/12881
- [x] Publish release 23.5.2 https://github.com/conda/conda/releases/tag/23.5.2
- [x] https://github.com/conda/conda/pull/12882
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/33
    - [x] https://github.com/conda-forge/conda-feedstock/pull/212
- [x] Hand off to the Anaconda packaging team

</details>

**Comment by kenodegard** [comment]
reopened since we identified a critical regression #12873
