### ISSUE TITLE
23.9 Deprecations/24.3 Removals

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#12681]
### Summary

Track features that are part of the conda 23.9 deprecations and eventual 24.3 removals

```[tasklist]
# Deprecations
- [ ] `conda.testing.integration.get_conda_list_tuple` (see #12676)
- [ ] `conda.testing.encode_for_env_var` (see #12677)
- [ ] `conda.testing.integration.temp_chdir` (see #12678)
- [ ] [`@memoized` decorator in `conda/export.py`](https://github.com/conda/conda/blob/28eb9aec0dd783f66420983d09514c7588d83269/conda/exports.py#L136-L166) is marked for deprecation ([in favor of `@lru_cache`](https://github.com/conda/conda/pull/11597))
- [ ] https://github.com/conda/conda/issues/12380
- [x] ~[loading subcommands from `conda-*` executables](https://github.com/conda/conda/blob/df7c74b41d29f8ec8dee83b92b49a2131d797a5f/conda/cli/conda_argparse.py#L145-L158)~ postponed to `25.3.0`
- [ ] [subdir_data/repodata deprecations](https://github.com/conda/conda/pull/12981)
- [ ] https://github.com/conda/conda/issues/13192
```
