### ISSUE TITLE
Problems caused by `current_repodata.json`

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#12718]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

There are currently quite a bit of issues related to the use of `current_repodata.json`. A lot of these issues are related to conda-forge, but they also occasionally affect users of defaults. This epic is an attempt to gather all of these to a single place.

The problem that our users often experience is that `mamba` will do one thing (typically the correct action from the perspective of the user) and `conda` will do another thing (typically the wrong thing).

The good news is that we have solutions for addressing this (multiple, in fact! 😎). The first is simply installing and configuring the `conda-libmamba-solver` (more information about that here: https://conda.github.io/conda-libmamba-solver/getting-started/) and the second is the new JLAP format (this is currently experimental so it's only recommend for users want to be and the bleeding edge). More information about JLAP can be found here: https://conda.org/blog/2023-05-05-how-we-reduced-the-conda-index-fetch-bandwidth/#ship-repodatajlap-incremental-repodata)

Once the JLAP feature moves out of experimental to stable, we should make sure to notify users on all the related issues so they are aware of yet another possible solution to their problem. We should also consider closing the issues too.

### Linked Issues & PRs

- [ ]  https://github.com/conda/conda/issues/12089
- [ ] https://github.com/conda/conda/issues/12640
- [ ] https://github.com/conda/conda/issues/12519
- [ ] https://github.com/conda/conda/issues/12390
