### ISSUE TITLE
Update testing CI

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#12772]
### Summary

A major overhaul of conda-build's tests.yml was completed earlier in the year and resulted in a much cleaner and more concise workflow recipe. Let's carry these improvements over and finish implementing:
- duration files for windows
- ~allure reports for all OSes~
- update caching to auto refresh every month

```[tasklist]
### Tasks
- [ ] #12773
- [ ] https://github.com/conda/conda/pull/12778
- [ ] https://github.com/conda/conda/pull/12780
- [ ] https://github.com/conda/conda/pull/12782
- [ ] https://github.com/conda-forge/allure-python-commons-feedstock/pull/21
- [ ] https://github.com/conda-forge/staged-recipes/pull/23089
- [ ] https://github.com/conda/conda/pull/12819
- [ ] https://github.com/conda/conda/pull/12820
- [ ] https://github.com/conda/conda/pull/13162
```

**Comment by travishathaway** [comment]
@kenodegard, is this epic complete?

**Comment by kenodegard** [comment]
Yup this is definitely finished now
