### ISSUE TITLE
Release 23.7.x

### ISSUE THREAD

**Issue by beeankha** [conda/conda#12849]
### Summary

| Pilot | @beeankha  |
|---|---|
| Co-pilot | @kenodegard  |

### Tasks

<details>
<summary><b>The week before release week</b></summary>

- [x] Create release branch named [`23.7.x`](https://github.com/conda/conda/tree/23.7.x)
- [x] Ensure release candidates are being successfully built (see [`conda-canary/label/rc-conda-23.7.x`](https://anaconda.org/conda-canary/conda/files?channel=rc-conda-23.7.x))
- [x] [Complete outstanding milestone items](https://github.com/conda/conda/milestone/61)
    - [x] https://github.com/conda/conda/issues/12903
    - [x] https://github.com/conda/conda/issues/12906
    - [x] https://github.com/conda/conda/issues/12907
- [x] Manual testing completed by @beeankha and @kenodegard 

</details>

<details>
<summary><b>Release week</b></summary>

- [x] Create release PR (see [release process](https://github.com/conda/conda/blob/main/RELEASE.md)) https://github.com/conda/conda/pull/12901
- [x] [Publish release](https://github.com/conda/conda/releases/tag/23.7.0)
- [x] https://github.com/conda/conda/pull/12921
- [x] Activate the `23.7.x` branch on [ReadTheDocs](https://readthedocs.com/projects/continuumio-conda/)
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/34
    - [x] https://github.com/conda-forge/conda-feedstock/pull/213
    - [x] https://github.com/conda-forge/conda-feedstock/pull/214
- [x] Hand off to the Anaconda packaging team
- [x] Announce release
    - Blog post
        - [x] https://github.com/conda-incubator/conda-dot-org/pull/158
        - [x] https://conda.org/blog/2023-07-28-july-2023-releases
    - Long form
        - [x] https://github.com/conda/communications/pull/20(https://github.com/conda/communications)
        - [x] [Discourse](https://conda.discourse.group/t/conda-23-7-2-conda-build-3-26-0-conda-libmamba-solver-23-7-0-conda-package-streaming-0-9-0-and-conda-package-handling-2-2-0-releases/361/2)
        - [x] [Matrix `conda/conda`](https://matrix.to/#/!SgckMCYyQUhdyooKZe:gitter.im/$3C2MoteRcEDIghkdfSChrGBS8uO1cbyLd-BKAy1pbNo?via=gitter.im&via=matrix.org&via=salt-rock-lamp.ems.host) (this auto posts from Discourse)
    - Summary
        - [x] [Twitter](https://twitter.com/condaproject/status/1688603431274184704)
        - [x] [Matrix (conda/conda-release)](https://matrix.to/#/!DDdyObfFXiuiRqHyFO:matrix.org/$jYt1YyrHopTDqIDXBFkgy8yJIHO34sCxPslthsTbPYs?via=matrix.org&via=gitter.im)

</details>

<details>
<summary><b>Hotfix 23.7.1</b></summary>

- [x] https://github.com/conda/conda/pull/12929
- [x] Create release PR (see [release process](https://github.com/conda/conda/blob/main/RELEASE.md)) https://github.com/conda/conda/pull/12930
- [x] [Publish release](https://github.com/conda/conda/releases/tag/23.7.1)
- [x] https://github.com/conda/conda/pull/12931
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/35
    - [x] https://github.com/conda-forge/conda-feedstock/pull/215
- [x] Hand off to the Anaconda packaging team

</details>

<details>
<summary><b>Hotfix 23.7.2</b></summary>

- [x] https://github.com/conda/conda/pull/12936
- [x] Create release PR (see [release process](https://github.com/conda/conda/blob/main/RELEASE.md)) https://github.com/conda/conda/pull/12939
- [x] [Publish release](https://github.com/conda/conda/releases/tag/23.7.2)
- [x] https://github.com/conda/conda/pull/12941
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/36
    - [x] https://github.com/conda-forge/conda-feedstock/pull/216
- [x] Hand off to the Anaconda packaging team

</details>

<details>
<summary><b>Hotfix 23.7.3</b></summary>

- [x] https://github.com/conda/conda/pull/13006
- [x] Create release PR (see [release process](https://github.com/conda/conda/blob/main/RELEASE.md)) https://github.com/conda/conda/pull/13009
- [x] [Publish release](https://github.com/conda/conda/releases/tag/23.7.3)
- [x] https://github.com/conda/conda/pull/13010
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/37
    - [x] https://github.com/conda-forge/conda-feedstock/pull/217
- [x] Hand off to the Anaconda packaging team

</details>

<details open>
<summary><b>Hotfix 23.7.4</b></summary>

- [x] Merge https://github.com/conda/conda/pull/13071
- [x] Merge https://github.com/conda/conda/pull/13082
- [x] Merge https://github.com/conda/conda/pull/13086
- [x] Merge https://github.com/conda/conda/pull/13088
- [x] Merge https://github.com/conda/conda/pull/13089
- [x] Merge https://github.com/conda/conda/pull/13090
- [x] Create release PR (see [release process](https://github.com/conda/conda/blob/main/RELEASE.md)) https://github.com/conda/conda/pull/13092
- [x] [Publish release](https://github.com/conda/conda/releases/tag/23.7.4)
- [x] https://github.com/conda/conda/pull/13093
- [x] https://github.com/conda/conda/pull/13094
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/38
    - [x] https://github.com/conda-forge/conda-feedstock/pull/218
- [x] Hand off to the Anaconda packaging team

</details>

**Comment by beeankha** [comment]
All task list items are complete! 🎉

**Comment by kenodegard** [comment]
Reopening for 23.7.3 patch release

**Comment by jezdez** [comment]
We need to do a 23.7.4 release to ship #13076 and #13071 as regression fixes.
