### ISSUE TITLE
Release 23.9.x

### ISSUE THREAD

**Issue by jezdez** [conda/conda#13080]
### Summary

Placeholder for `conda 23.9.x` release.

| Pilot | @jezdez |
|---|---|
| Co-pilot | @kenodegard |

### Tasks

[milestone]: https://github.com/conda/conda/milestone/63
[process]: https://github.com/conda/conda/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda/releases
[main]: https://github.com/AnacondaRecipes/conda-feedstock
[conda-forge]: https://github.com/conda-forge/conda-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda/

<details>
<summary><h4>The week before release week</h4></summary>

- [x] Create release branch (named `23.9.x`)
- [x] Ensure release candidates are being successfully built (see `conda-canary/label/rc-conda-23.9.x`)
- [x] [Complete outstanding PRs][milestone]
- [x] Test release candidates [commits](https://github.com/conda/conda/compare/23.7.4...23.9.x) inline (without pre-commit, test duration changes):
  - [x] 1a1e95854adc74c481adffde4810550002dfec7e Update recipe metadata dependencies (#13141)
  - [ ] 7a777b8a2e2e5b6d1dadc21c45fb90c9fc35bbe2 Source bash files in non-interactive mode (#13012)
  - [x] 2745211e70436a3b7f4bd116fa3c578d4579866e Use `conda-forge::minio-server` (#13084)
  - [x] ef9a5734528809d2ec295edf223b7c8715a4474e More refactoring for plugin manager. (#13118)
  - [x] ec2cdda8aef5d68937c8e6cd7df1d2c6a8d892a6 MatchSpec warning was missing the f-prefix for the string (#13051)
  - [x] af87ce22a53b8b29d45b2dd21c4acb509a856df1 Use OS Truststore in corporate HTTPS inspection proxies (#13075)
  - [x] 2e63919f95a07abe17e16bd1227632c63a0b5cc6 Lazily import boto3 within method (#13126)
  - [x] 32647334148ab4d2109656954d602648eb7be95b Catch OSError in find_commands (#13127)
  - [x] e4686058727df0fabc5e1669c97d54462f72c548 Show git diff after all pre-commit hooks to be able to see auto-format/fix changes (#13124)
  - [x] dea94d4a339c35f531d686108862002054222153 Fix typo in conda_argparse.py (#13123)
  - [x] d1dacb9d1c4ef1ebb26d1406da3e965ccc6d159c Use ruff (#12279)
  - [x] d328e743d1ef9d4627c7a6ee13fefbd0e3a046b7 prefer log.warning() in conda.gateways.repodata (#13108)
  - [x] 429df905dcca3b62e47602cab30c1531037d4d07 clarify changelog (#13119)
  - [x] c5057099b55ea46312fd1fe66a265cb953f22888 Remove code for unsupported boto library (boto3 remains) (#13112)
  - [x] aecd96e9af3fca7f08898c4d6af476af255a84e8 reindex test repository, fixing checksums (#13111)
  - [x] 68a998b4d44d91e76d3a68015dbbbd776af85241 Add a py.typed marker (#13107)
  - [x] 9a23bc4d6e19b2a913a10e8e382dfb3b97152730 Fix mistake in doc string (#13074)
  - [x] 6d0d003b727c5ac10912c37eb998e9b66d9b988e Move all pluggy specifics into the manager (#13057)
  - [x] e658798dc1e94b574660e13729ac9ec7b093038c Add healthcheck for checking whether the environment is listed on environments.txt (#13000)
  - [ ] c76f5aa0ba595e7aeca9f0c077f614f4dc7cf06d catch JSONDecodeError when loading repodata cache metadata (#13101)
  - [x] 3324ec9da186a6cc07f0009e976452bdaafcaa56 Fix conda remove all json (#13021)
  - [x] 50a7272a5cc79204b6471afa269df44fa765334c Install anaconda-client from conda-forge for tests (#13099)
  - [x] fb7775e936cdc1e9996d31662ad1c0c356bd9b1f Add emscripten-wasm32 and wasi-wasm32 platforms to known platforms (#13095)
  - [x] 1e5d73709748f142c929c97e98dc725875059d09 Merge pull request #13094 from conda/23.7.x-resolve-conflict
  - [x] bf39e8d9e6075382c76da10288a1f8606226cac5 Merge branch 'main' into 23.7.x
  - [x] cc1dc072895224949b9999a526a397f1e0f4e864 Fix context mocking for CondaSession test (#13087)
  - [x] 8faf745567b93e8112003b934bbe4b9191c16506 Fix key sorting for `json.dumps` in `conda config` (#13076)
  - [x] 0a2244f0995be1f7f5759bb6c19ea8c3393ec099 Update `test_main_clean.py` to use zlib instead of bzip2 (#13065)
  - [x] e9870ccaaa1ee1c57ff38b075f308e6c051c72a7 defer cgi import when ftp is not used (#13014)
  - [x] adcf8ef6f268cf8f77cf2b433d1ccf56fad94bdb configuring retry behavior to ignore "retry-after" headers (#13050)
  - [x] 74f5e6395fa52fda772fed452fa1fa4d7219b596 Disallow ability to create a conda env with `:` in the prefix (#13044)
  - [x] 417b797e5f44fec5a96ff54f7a25ccf956209767 Extract static pytest args into config (#13048)
  - [x] 5c814f97ac02af80477eaf89229a7c2b66814ca0 Catch a write permission errors when creating the package cache directory (#10841)
  - [x] ee952a8b2cd443b5af5da38f9dc5557ef43d9a3f Update `run_command` tests with `conda_cli` (#12974)
  - [ ] eb268dc18b6e62a4a779ef2884e49c4c903e47f0 Check if directory is writable with running conda env create (#11610)
  - [x] 34dfb1fd38180de48f836c0c4e03017fc10feb1a Replace `flake` package spec for test (#13034)
  - [x] db8f1c3580bf597458bebc787498b05ae9a5f0c7 Fix `conda info --all` (#13036)
  - [ ] ae409f81d189411f02801999871a313095e5f352 Speed up find_commands() on WSL (#13035)
  - [x] 1e0f89c371f09511e415fae29aa7bd2292021742 Add a config option for environment registration (#12924)
  - [x] 8d7f508720b46ba3069178a753d7193bfcd3e3bb Fix typo in activation.md (#13039)
  - [x] 3f4a634512d91b22c781dd4763738c70a1ab8344 Directly suppress use of binstar token when fetching trust metadata (#12889)
  - [x] 95e90f63516fa95ac013c2ea6919beafb8779067 Ignore setup output for `tests/test_activate.py::test_stacking` (#13025)
  - [x] 68a7dc9b85a3598fea1aba9eb73bfa2fc796eb40 Inject new detailed verbosity level (#12985)
  - [x] b53705b1e8000ead53bdb582705928fdc5932fbd Auth handler plugin hook (#12911)
  - [x] 1313ef5ad4d9e0f519ff6735fceea266be77f6d5 Add 'tag::update' label in order to keep track of update issues (#13028)
  - [x] 0558e7838820bd8edebefe66136456a81e00ff2d Do not show download bars in non interactive runs (#12982)
  - [x] a26db05d5abd10a251128e2ce5092e7e8bb72f46 Remove 23.9.0 deprecations (#12948)
  - [x] 20e621729a03df6bd3d1515554e4eb97363afae3 Lock repodata cache by default (#12996)
  - [x] fa5c4940ea5c40004a440cdb1a217e374778bede Handle jlap response without request e.g. for file:/// (#12994)
  - [x] 4fa4e4a4ee6c24997d79feb7c0419e0939f62ab0 gateways/repodata: remove load/save/read_mod_and_etag (#12981)
  - [x] 9c7af409af591451de685f1781130f1aab37acb5 Make `conda env update --prune` ignore history specs. (#9614)
  - [x] 79c952f86691b905a21c006a980cbf3cfac70ef0 Merge pull request #13010 from conda/23.7.x
  - [x] 07049ac7d47aebe555d24d6d610d54379d87b3a2 Remove MinIO pin (#12992)
  - [x] 5093abd1dcfa95378653fc5f8edf0f1770720e21 Default `--json` & `--debug` to `NULL` (#12988)
  - [x] b6886dd5644f96e80220a44b1d85f5d7ead66e57 Fix `test_s3_server` failure (#12986)
  - [x] 884e41f759f6a08ace0f8a1308ffd44560fa60d9 Port doctor CLI tests to conda_cli fixture. (#12950)
  - [x] 76bc537cb1ef7bab8b6c940d06ffb8a7deb51fdb Refactor private channel test (#12961)
  - [x] 0973c1b61b342cd9c7d76ee3729b0716325b77a1 fixing broken commands links (#12962)
  - [x] 95c9545b8d0cfc45659610e88e5d9e16c76035bd [docs] Update manage-environments.rst (#12835)
  - [x] ab110eb749804b9c67f6c1ae9ca0a6e044cde765 Bump default devenv Python to 3.10 (#12951)
  - [x] 90be21d9d93329724cedb99b3960f279c8b75dfd add note about yaml extension in .condarc docs (#12946)
  - [x] df7c74b41d29f8ec8dee83b92b49a2131d797a5f Merge pull request #12941 from conda/23.7.x
  - [x] 1b3f8a20835b5f554b5dc1b2efb9f087903c78b8 remove cache_path_* arguments (#12927)
  - [x] 416993b967db33a22b1270bc83e10aa6f71c8bba Increase timeout for activation test on conda-forge. (#12932)
  - [x] 08c0ab8ab54ec91eca037a73e89021a4014fbac9 jlap: disable warning when not context.ssl_verify (#12923)
  - [x] 1b53c20dab60a262a87d21ed3609430117ff7e18 Merge pull request #12931 from conda/23.7.x
  - [x] 6d5f7556a5751efc606e11811191b5a2e7b59a55 Update conda recipe file (#12922)
  - [x] 0ac1716ed766599f9f4bfbcf275bd8a1b84841ee Merge pull request #12921 from conda/23.7.x
  - [x] 26c648831b4606bc4fd1ae575199fb611d6e7ff5 replace inspect.stack() with sys._getframe() to save ~170ms -> ~90ms (#12919)
  - [x] bf5876c23fb33c014846c554d10c16c175313539 lazy-load boto3 to save ~400ms startup time (#12914)
  - [x] 14d611af65cfa17fd9a4945abe3296d382eaa48e Parametrize `test_priority.py` (#12895)
  - [x] 08c7ed6618d68db0b004deacb968780cb6eb1016 Optimize conda_initialize_content for fish-shell, improve the 400x speed (#12811)

</details>

#### Release week

- [x] Create release PR (https://github.com/conda/conda/pull/13153)
- [x] [Publish release][releases] (https://github.com/conda/conda/releases/tag/23.9.0)
- [x] https://github.com/conda/conda/pull/13155
- [x] Activate the `23.9.x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/40
    - [x] https://github.com/conda-forge/conda-feedstock/pull/220
    - [x] https://github.com/conda-forge/conda-feedstock/pull/221
    
- [x] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [x] conda.org https://github.com/conda-incubator/conda-dot-org/pull/163
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [x] [Twitter](https://twitter.com/condaproject) https://x.com/condaproject/status/1713912930390208519?s=20
        - [ ] Matrix (conda/conda-release)

**Comment by JennPlothow** [comment]
Duplicate of #
[LICENSE.txt](https://github.com/conda/conda/files/12645191/LICENSE.txt)

**Comment by wuillaum** [comment]
Is there a separate process within `Hand off to the Anaconda packaging team` for getting a new miniconda release out? I tried [scouring the docs](https://docs.conda.io/projects/miniconda/en/latest/) for any info on miniconda's release cadence, maintenance schedule, etc. but all I could find was the repo index which tells me the last release was back in July https://repo.anaconda.com/miniconda/ for 23.5

Any chance a new version could be published for 23.9.x?

**Comment by wuillaum** [comment]
Any update on the miniconda release @jezdez ? :sweat_smile:
