### ISSUE TITLE
Release 23.10.x

### ISSUE THREAD

**Issue by jezdez** [conda/conda#13156]
### Summary

Placeholder for `conda 23.10.x` release.

Refs https://github.com/conda/conda-libmamba-solver/issues/350

| Pilot | @jezdez |
|---|---|
| Co-pilot | @jaimergp |

### Tasks

[milestone]: https://github.com/conda/conda/milestone/67
[process]: https://github.com/conda/conda/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda/releases
[main]: https://github.com/AnacondaRecipes/conda-feedstock
[conda-forge]: https://github.com/conda-forge/conda-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda/

#### The week before release week

- [x] Create release branch (named `23.10.x`)
- [x] Ensure release candidates are being successfully built (see `conda-canary/label/rc-conda-23.10.x`)
- [x] [Complete outstanding PRs][milestone]
- [x] Test release candidates
    

#### Release week

- [x] Create release PR #13261 
- [x] [Publish release][releases] https://github.com/conda/conda/releases/tag/23.10.0
- [x] https://github.com/conda/conda/pull/13286
- [x] Activate the `23.10.x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/41
    - [x] https://github.com/conda-forge/conda-feedstock/pull/224
    
- [x] Hand off to the Anaconda packaging team
- [x] Announce release
    - Blog Post
        - [x] conda.org https://github.com/conda-incubator/conda-dot-org/pull/166
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [x] [Twitter](https://twitter.com/condaproject) https://x.com/condaproject/status/1721660179098505425

**Comment by jakirkham** [comment]
Congratulations on the release! 🥳

This is a huge milestone 🙏

Now that everything is tagged and published, is there anything still needed for this issue?

**Comment by thomasdziedzic-calmwave** [comment]
I saw that 23.10 was released but when I looked for it in asdf, it wasn't available. This led me to finding out that this release isn't listed on https://repo.anaconda.com/miniconda/

Could this release be added there so that asdf-python (pyenv python-build behind the scenes) is able to pick it up?

**Comment by jezdez** [comment]
The miniconda distribution is separate from the conda release, but is planned to be released soon (next ~2 weeks). Just not as part of this particular repo. Thank you for your patience!

**Comment by jaimergp** [comment]
It actually became available last night! https://docs.conda.io/projects/miniconda/en/latest/#id2
