### ISSUE TITLE
Deprecate `conda.models.dist.Dist`

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#13192]
### What is the idea?

`conda.models.dist.Dist` is a legacy implementation of `conda.models.records.PackageRecord`. It and related functionality appears to have been left around for conda_build's sake. Let's make an effort to update conda_build as necessary so we can mark this for deprecation.

### Why is this needed?

Remove unused legacy code.

### What should happen?

Mark `conda.models.dist.Dist` as deprecated.

```[tasklist]
### Tasks
- [ ] Deprecate `conda.models.dist.Dist`
- [ ] https://github.com/conda/conda/pull/13193
- [ ] Deprecate `conda.exports.get_index`
- [ ] https://github.com/conda/conda/pull/13194
- [ ] Deprecate `conda.exports.package_cache`
- [ ] Deprecate `conda.exports.linked_data`
- [ ] Deprecate `conda.exports.linked`
- [ ] https://github.com/conda/conda-build/issues/5069
```

**Comment by tysonclugg** [comment]
Be aware of https://github.com/conda/conda-build/issues/4991 - this issue _might_ be a release blocker for _all_ of `conda-build`, `conda`, and `conda-libmamba-solver` packages.  Particularly with the [special announcement](https://github.com/conda/conda/blob/main/CHANGELOG.md#special-announcement) regarding the imminent change of the default solver.

@jezdez - your thoughts?
