### ISSUE TITLE
Perform a refactor of the user guide

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#13283]
### What is the idea?

We want to re-envision the user guide so that its content is useful for readers and easy to digest.

### What should happen?

Go through existing pages in the "User Guide" section and make note of:

- Out of date examples
- Confusing guides
- Index pages (section landing pages) that could be organized better (e.g. https://docs.conda.io/projects/conda/en/stable/user-guide/index.html)
- General user improvements (where could improved UI elements placed such as buttons?)
- Do not break links! Make sure to setup redirects where necessary.

### Tasks

- [ ] Remove the sentence about Conda Basics and put a link to that course inside "Additional Resources".
- [ ] Remove "See what conda is and what it does" section (it simply links to the conda home page!)
- [ ] Create an "Updating conda" section inside the user guide
- [ ] Change "Create your first conda project in 20 minutes" to "Create your first project using conda in 20 minutes".
- [ ] Clarify "when to use conda's user guide and when Anaconda distribution's user guide". See [this](https://github.com/conda/conda/issues/13283#issuecomment-1831122901) comment.
- [ ] Update [Installing with conda - Conda update versus conda install](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/installing-with-conda.html#conda-update-versus-conda-install) with a different example (the current one is not correct).

**Comment by ForgottenProgramme** [comment]
The User Guide has a top menu with all it's content headings plus "Home" which links to [conda docs home page](https://docs.conda.io/projects/conda/en/latest/index.html). 
I think this is unnecessary. 

<img width="710" alt="Screenshot 2023-11-13 at 1 43 59 PM" src="https://github.com/conda/conda/assets/65779580/e1cab58e-b2e9-4489-9c41-9f705f98c80c">

**Comment by ForgottenProgramme** [comment]
Under "Get started" the "see what is conda and what it does" again links to conda docs home page! :facepalm:

<img width="679" alt="Screenshot 2023-11-13 at 1 50 03 PM" src="https://github.com/conda/conda/assets/65779580/a479a785-ade0-408d-89e6-2f3a21b8f5ce">

**Comment by ForgottenProgramme** [comment]
Per an internal discussion, adding a "Updating Conda" section in the User Guide might be a good idea.

**Comment by ForgottenProgramme** [comment]
The User Guide has this line:
```
Looking for more information on conda? Anaconda has a free Conda Basics course in Anaconda Learning.
```

I think we can remove this sentence and put a link to the Conda Basics course under "Additional Resources".

**Comment by ForgottenProgramme** [comment]
"conda project" could be a bit misleading and confusing. 
Changing it to "project using conda" might be a better.
<img width="691" alt="Screenshot 2023-11-16 at 4 37 01 PM" src="https://github.com/conda/conda/assets/65779580/6f0a2ef9-b9f4-4525-9ee0-85266761ab3d">

**Comment by ForgottenProgramme** [comment]
Clicking on "Additional Resources" in the top menu on User Guide page doesn't do anything.

**Comment by ForgottenProgramme** [comment]
I think thats the commit number displayed after "Revision". We don't need that. 

<img width="596" alt="Screenshot 2023-11-28 at 10 52 09 AM" src="https://github.com/conda/conda/assets/65779580/14a0cfeb-0fae-4f59-a7cb-2ca0de3ac33b">

**Comment by rootsmusic** [comment]
> Instead right after "User Guide" main heading we can put a small paragraph about what conda is.

@ForgottenProgramme  As a user, I'm unsure when to reference conda's user guide or Anaconda Distribution's user guide.  (Although conda was installed on my PC by Anaconda Distribution, I thought that I should reference conda's user guide when using the conda package to run CLI commands.)  So I suggest explaining when users should reference which user guide.

**Comment by ForgottenProgramme** [comment]
That's a great suggestion, @rootsmusic. Thank you.

**Comment by travishathaway** [comment]
@ForgottenProgramme,

I found a new one today:

- https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/installing-with-conda.html#conda-update-versus-conda-install

The information there is not accurate. If you perform a `conda update python` when `python=2.7` is install it updates to the latest `3.x` version. This should be replaced by a different example explaining the differences between `conda update` and `conda install`.

**Comment by rootsmusic** [comment]
> Clarify "when to use conda's user guide and when Anaconda distribution's user guide". See [this](https://github.com/conda/conda/issues/13283#issuecomment-1831122901) comment.

@ForgottenProgramme  Since the User Guide doesn't have a page for "help and support".  I added this task to [my issue](https://github.com/conda/conda-docs/issues/915) about that page.

P.S. if the User Guide is audited page by page, then this issue wouldn't need to be labelled "epic".

**Comment by rootsmusic** [comment]
Please add a section/page about how to [deal with dependency conflicts](https://pip.pypa.io/en/stable/topics/dependency-resolution/#dealing-with-dependency-conflicts).
