### ISSUE TITLE
Modernize `tests/test_create.py`

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#13292]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

`tests/test_create.py` contain 102 tests. A lot of them contain outdated testing functionality and needs updating. Several prior attempts have been made to update this file but each effort failed as theres simply too many tests to do all at once. Let's instead take this piecemeal and do one at a time.

### Linked Issues & PRs

- [ ] `test_install_python_and_search`
- [ ] `test_run_preserves_arguments`
- [ ] `test_create_install_update_remove_smoketest`
- [ ] `test_install_broken_post_install_keeps_existing_folders`
- [ ] `test_safety_checks`
- [ ] `test_json_create_install_update_remove`
- [ ] `test_not_writable_env_raises_EnvironmentNotWritableError`
- [ ] `test_conda_update_package_not_installed`
- [ ] `test_noarch_python_package_with_entry_points`
- [ ] `test_noarch_python_package_without_entry_points`
- [ ] `test_noarch_python_package_reinstall_on_pyver_change`
- [ ] `test_noarch_generic_package`
- [ ] `test_override_channels`
- [ ] `test_create_empty_env`
- [ ] `test_strict_channel_priority`
- [ ] `test_strict_resolve_get_reduced_index`
- [ ] `test_list_with_pip_no_binary`
- [ ] `test_list_with_pip_wheel`
- [ ] `test_compare_success`
- [ ] `test_compare_fail`
- [ ] `test_install_tarball_from_local_channel`
- [ ] `test_tarball_install`
- [ ] `test_tarball_install_and_bad_metadata`
- [ ] `test_update_with_pinned_packages`
- [ ] `test_pinned_override_with_explicit_spec`
- [ ] `test_remove_all`
- [ ] `test_allow_softlinks`
- [ ] `test_remove_features`
- [ ] `test_dash_c_usage_replacing_python`
- [ ] `test_install_prune_flag`
- [ ] `test_remove_force_remove_flag`
- [ ] `test_install_force_reinstall_flag`
- [ ] `test_create_no_deps_flag`
- [ ] `test_create_only_deps_flag`
- [ ] `test_install_update_deps_flag`
- [ ] `test_install_only_deps_flag`
- [ ] `test_install_update_deps_only_deps_flags`
- [ ] `test_install_features`
- [ ] `test_clone_offline_simple`
- [ ] `test_conda_config_describe`
- [ ] `test_conda_config_validate`
- [ ] `test_conda_config_validate_sslverify_truststore`
- [ ] `test_rpy_search`
- [ ] `test_compile_pyc`
- [ ] `test_conda_run_1`
- [ ] `test_conda_run_nonexistant_prefix`
- [ ] `test_conda_run_prefix_not_a_conda_env`
- [ ] `test_clone_offline_multichannel_with_untracked`
- [ ] `test_package_pinning`
- [ ] `test_update_all_updates_pip_pkg`
- [ ] `test_package_optional_pinning`
- [ ] `test_update_deps_flag_absent`
- [ ] `test_update_deps_flag_present`
- [ ] `test_shortcut_in_underscore_env_shows_message`
- [ ] `test_shortcut_not_attempted_with_no_shortcuts_arg`
- [ ] `test_shortcut_creation_installs_shortcut`
- [ ] `test_shortcut_absent_does_not_barf_on_uninstall`
- [ ] `test_shortcut_absent_when_condarc_set`
- [ ] `test_create_default_packages`
- [ ] `test_create_default_packages_no_default_packages`
- [ ] `test_create_dry_run`
- [ ] `test_create_dry_run_json`
- [ ] `test_create_dry_run_yes_safety`
- [ ] `test_packages_not_found`
- [ ] `test_conda_pip_interop_dependency_satisfied_by_pip`
- [ ] `test_conda_pip_interop_pip_clobbers_conda`
- [ ] `test_conda_pip_interop_conda_editable_package`
- [ ] `test_conda_pip_interop_compatible_release_operator`
- [ ] `test_install_freezes_env_by_default`
- [ ] `test_search_gawk_not_win_filter`
- [ ] `test_search_gawk_on_win`
- [ ] `test_search_gawk_on_win_filter`
- [ ] `test_bad_anaconda_token_infinite_loop`
- [ ] `test_anaconda_token_with_private_package`
- [ ] `test_use_index_cache`
- [ ] `test_offline_with_empty_index_cache`
- [ ] `test_create_from_extracted`
- [ ] `test_install_mkdir`
- [ ] `test_disallowed_packages`
- [ ] `test_dont_remove_conda_1`
- [ ] `test_dont_remove_conda_2`
- [ ] `test_force_remove`
- [ ] `test_download_only_flag`
- [ ] `test_transactional_rollback_simple`
- [ ] `test_transactional_rollback_upgrade_downgrade`
- [ ] `test_directory_not_a_conda_environment`
- [ ] `test_multiline_run_command`
- [ ] `test_create_env_different_platform_cli_flag`
- [ ] `test_create_env_different_platform_env_var`
- [ ] `test_conda_downgrade`
- [ ] `test_run_script_called`
- [ ] `test_post_link_run_in_env`
- [ ] `test_conda_info_python`
- [ ] `test_toolz_cytoolz_package_cache_regression`
- [ ] `test_remove_spellcheck`
- [ ] `test_conda_list_json`
- [ ] `test_legacy_repodata`
- [ ] `test_cross_channel_incompatibility`
- [ ] `test_neutering_of_historic_specs`
- [ ] `test_install_bound_virtual_package`
- [ ] `test_remove_empty_env`
- [ ] `test_remove_ignore_nonenv`

**Comment by jaimergp** [comment]
Awesome! TBH some of these tests are strictly solver tests that need no IO at all. I've been thinking about how to do this in a clean way that is also tool agnostic, since `test_create` is one of the "ground truths" for correct solver compliance.

I'd like to hear your thoughts on some ideas, namely:

* Using packaged repodata as the only solver repodata source. Download once as a test dependency, do not touch it again and operate offline after that.
* Using JSON documents to codify solver transactions and their expected outcomes.
* Assigning a number to each test case, e.g. `test_0001_add_python`.
* Having some helpers to mock the expected state (installed packages, state, etc). There are several attempts in the test suite, but none of them is feature complete. These helpers should be importable and subclassable so other implementations can redefine certain primitives (in-process and subprocess).

We would also take `tests/core/test_solve.py` there. If this is not the right place to post this issue, apologies! I can recreate if needed.

**Comment by kenodegard** [comment]
woohoo!! 50% completed

**Comment by kenodegard** [comment]
All done!
