### ISSUE TITLE
Release 23.11.x

### ISSUE THREAD

**Issue by jezdez** [conda/conda#13324]
### Summary

Placeholder for `conda 23.11.x` release.

| Pilot | @jezdez |
|---|---|
| Co-pilot | @kenodegard |

### Tasks

[milestone]: https://github.com/conda/conda/milestone/64
[process]: https://github.com/conda/conda/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda/releases
[main]: https://github.com/AnacondaRecipes/conda-feedstock
[conda-forge]: https://github.com/conda-forge/conda-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda/

<details>
<summary><h4>The week before release week</h4></summary>

- [x] Create release branch (named `23.11.x`)
- [x] Ensure release candidates are being successfully built (see [`conda-canary/label/rc-conda-23.11.x`](https://anaconda.org/conda-canary/conda/files?channel=rc-conda-23.11.x))
- [x] [Complete outstanding PRs][milestone]
- [x] Test release candidates
    - [x] #13210
    - [x] #13218
    - [x] #13232
    - [x] #13191
    - [x] #13173
    - [x] #13213
    - [x] #13231
    - [x] #13249
    - [x] #13171
    - [x] #13258
    - [x] #13263
    - [x] #13246
    - [x] #13279
    - [x] #13186
    - [x] #13307
    - [x] #13211
    - [x] #13313
    - [x] #13266
    - [x] #13317
    - [x] #13329
    - [x] #13346
    - [x] #13357
    - [x] #11882

</details>

<details open>
<summary><h4>Release week</h4></summary>

- [x] Create release PR (see [release process][process]) https://github.com/conda/conda/pull/13382
- [x] [Publish release][releases] https://github.com/conda/conda/releases/tag/23.11.0
- [x] https://github.com/conda/conda/pull/13383
- [x] https://github.com/conda/conda/pull/13393
- [x] https://github.com/conda/conda/pull/13394
- [x] https://github.com/conda/conda/pull/13397
- [x] Activate the `23.11.x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/42
    - [x] https://github.com/conda-forge/conda-feedstock/pull/228
    
- [x] Hand off to the Anaconda packaging team
- [x] Announce release
    - Blog Post (optional)
        - [x] https://github.com/conda-incubator/conda-dot-org/pull/170
    - Long form
        - [x] https://github.com/conda/communications/pull/24
        - [x] [Discourse](https://conda.discourse.group/) https://conda.discourse.group/t/november-releases-conda-23-11-0-conda-build-3-28-1-and-conda-libmamba-solver-23-11-1/456?u=kenodegard
        - [x] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [x] [Twitter](https://twitter.com/condaproject) https://x.com/condaproject/status/1732830642168340557

</details>
