### ISSUE TITLE
Post-menuinst-v2 tasks

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#13371]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

With https://github.com/conda/conda/pull/11882 merged, there are some cleanup tasks to do to finalize the migration. This must happen _after_ 23.11 has been released. 

### Linked Issues & PRs

- [ ] Revert CI workflow hacks where `menuinst` is installed from URLs directly (both in conda _and_ conda-build)
- [ ] Edit requirements files to reflect the new `menuinst` dependency on all platforms
