### ISSUE TITLE
Epic: `rename`/prefix-related fixes

### ISSUE THREAD

**Issue by beeankha** [conda/conda#13396]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

This epic groups together a few issues related to placing guardrails against dangerous prefix paths as well as refactoring the `main_rename.py` module. All of these efforts are a result of research that was done for fixing the following bug:
* https://github.com/conda/conda/issues/13271

### Linked Issues & PRs

- [x] #13271 (
  - [ ] #13280)
  - [x] https://github.com/conda/conda/pull/13955
- [x] #13386
  - [x] #13387
- [x] #13395 
- [x] #11850
