### ISSUE TITLE
Release 24.1.x

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#13486]
### Summary

Placeholder for `conda 24.1.0` release.

| Pilot | @jezdez |
|---|---|
| Co-pilot | @kenodegard |

### Tasks

[milestone]: https://github.com/conda/conda/milestone/65
[process]: https://github.com/conda/conda/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda/releases
[main]: https://github.com/AnacondaRecipes/conda-feedstock
[conda-forge]: https://github.com/conda-forge/conda-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda/

<details>
<summary><h4>The week before release week</h4></summary>

- [x] Create release branch (named `24.1.x`)
- [x] Ensure release candidates are being successfully built (see `conda-canary/label/rc-conda-24.1.x`)
- [x] [Complete outstanding PRs][milestone]
  - [x] https://github.com/conda/conda/pull/13539
  - [x] https://github.com/conda/conda/pull/13530
- [x] Test release candidates
  - [x] #13338
  - [x] #13419
  - [x] #13318
  - [x] #13168
  - [x] #13053
  - [x] #13440
  - [x] #13483
  - [x] #13452
  - [x] #13455
  - [x] #13504
  - [x] #13387
  - [x] #13520
  - [x] #13521
  - [x] #13530
  - [x] tested by @kenodegard on osx-64
  - [x] tested by @jezdez on windows

</details>

<details open>
<summary><h4>Release week</h4></summary>

- [x] https://github.com/conda/conda/pull/13524 (see [release process][process])
- [x] https://github.com/conda/conda/releases/tag/24.1.0 ([Publish release][releases])
- [x] https://github.com/conda/conda/pull/13544
- [x] Activate the `24.1.x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/43
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/44
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/45
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/46
    - [x] https://github.com/conda-forge/conda-feedstock/pull/229
    
- [x] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [x] https://github.com/conda-incubator/conda-dot-org/pull/175
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)

</details>

<details>
<summary><h4>Hotfix 24.1.1</h4></summary>

- [x] https://github.com/conda/conda/issues/13573
- [x] https://github.com/conda/conda/pull/13588
- [x] https://github.com/conda/conda/pull/13590 (see [release process][process])
- [x] https://github.com/conda/conda/releases/tag/24.1.1 [Publish release][releases]
- [x] https://github.com/conda/conda/pull/13591
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/47
    - [x] https://github.com/conda-forge/conda-feedstock/pull/230
- [x] Hand off to the Anaconda packaging team

</details>

<details>
<summary><h4>Hotfix 24.1.2</h4></summary>

- [x] https://github.com/conda/conda/issues/13595
- [x] https://github.com/conda/conda/pull/13599 (see [release process][process])
- [x] https://github.com/conda/conda/releases/tag/24.1.2 [Publish release][releases]
- [x] https://github.com/conda/conda/pull/13606
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/48
    - [x] https://github.com/conda-forge/conda-feedstock/pull/231
- [x] Hand off to the Anaconda packaging team

</details>
