### ISSUE TITLE
`conda update` issues

### ISSUE THREAD

**Issue by ForgottenProgramme** [conda/conda#13570]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

This epic attempts to collect all `conda update` related issues in one place. 
The issues have been organized based on the month/year they were reported in. This allows us to make informed observations about the frequency of such issues, for example, does the frequency of such reports increase post a new conda release? 

### Linked Issues & PRs

**Jan 2024**
- [ ] https://github.com/conda/conda/issues/13519 

**Aug 2023**

- [ ] https://github.com/conda/conda/issues/12983 
- [ ] https://github.com/conda/conda/issues/12967 
- [ ] https://github.com/conda/conda/issues/12964

**Jul 2023**

- [ ] https://github.com/conda/conda/issues/12898

**Jun 2023**

- [ ] https://github.com/conda/conda/issues/12833 
- [ ] https://github.com/conda/conda/issues/12832 
- [ ] https://github.com/conda/conda/issues/12828 
- [ ] https://github.com/conda/conda/issues/12801 
- [ ] https://github.com/conda/conda/issues/12759

**May 2023**

- [ ] https://github.com/conda/conda/issues/12729 

**Apr 2023**

- [ ] https://github.com/conda/conda/issues/12570 
- [ ] https://github.com/conda/conda/issues/12868 

**Mar 2023**

- [ ] https://github.com/conda/conda/issues/12519
- [ ] https://github.com/conda/conda/issues/12456

**Feb 2023**

- [ ] https://github.com/conda/conda/issues/12342

**Jan 2023**

- [ ] https://github.com/conda/conda/issues/12229 

**Dec 2022**

- [ ] https://github.com/conda/conda/issues/12166 

**Oct 2022**

- [ ] https://github.com/conda/conda/issues/11942 

**July 2022**

- [ ] https://github.com/conda/conda/issues/11618 

**Mar 2022**

- [ ] https://github.com/conda/conda/issues/11300

**Feb 2022**

- [ ] https://github.com/conda/conda/issues/11196 

**Dec 2021**

- [ ] https://github.com/conda/conda/issues/11083 

**Aug 2021**

- [ ] https://github.com/conda/conda/issues/10877 

**Apr 2020**

- [ ] https://github.com/conda/conda/issues/9899

**Comment by ForgottenProgramme** [comment]
TODO:
I will now go through these issues one by one and categorize them based on any patterns I notice.
