### ISSUE TITLE
FileNotFoundError / "filename too long" issues

### ISSUE THREAD

**Issue by ForgottenProgramme** [conda/conda#13575]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

This epic collects issues due to the "FileNotFoundError('The filename or extension is too long')" error on Windows.

### Linked Issues & PRs

- [ ] https://github.com/conda/conda/issues/7203
- [ ] https://github.com/conda/conda/issues/10767
- [ ] https://github.com/conda/conda-build/issues/5122

**Comment by traversaro** [comment]
A few of my colleagues were quite puzzled by the error:

~~~
InvalidArchiveError("Error with archive C:\\Users\\apaolino\\AppData\\Local\\miniforge3\\pkgs\\pytorch-2.6.0-cuda126_mkl_py313_h623afa4_304.conda.  You probably need to delete and re-download or re-create thi)
~~~

While most of the discussion in https://github.com/conda/conda/issues/7203 seems to focus on ways of automatically setting the `LongPathsEnabled` regedit variable (that is inherently complex as it requires administrative rights) I think the situation can be radically improved by improving the error message, printing a user warning if it is detected that `LongPathsEnabled` is not enabled, and leaving to the user the step of actually setting the variable.
