### ISSUE TITLE
Release 24.3.x

### ISSUE THREAD

**Issue by beeankha** [conda/conda#13638]
### Summary

Placeholder for conda 24.3.x releases.

| Role | Person |
|---|---|
| Pilot | @jezdez |
| Co-pilot | @beeankha |
| Jumpseat / Pilot in Training | @ForgottenProgramme  |

### Tasks

[milestone]: https://github.com/conda/conda/milestone/66
[process]: https://github.com/conda/conda/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda/releases
[main]: https://github.com/AnacondaRecipes/conda-feedstock
[conda-forge]: https://github.com/conda-forge/conda-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda/

#### The week before release week

- [x] Create release branch (named `24.3.x`)
- [x] Ensure release candidates are being successfully built (see `conda-canary/label/rc-conda-24.3.x`)
- [x] [Complete outstanding PRs](https://github.com/conda/conda/milestone/66)
- [x] Test 24.3.0 release candidate
  * [x] add zstandard as a run dependency by @dholth in https://github.com/conda/conda/pull/13551
  * [x] Fix conda pre, post and health check plugin examples by @jjhelmus in https://github.com/conda/conda/pull/13556
  * [x] Use conda_cli fixture by @dholth in https://github.com/conda/conda/pull/13547
  * [x] Remove `--no-test` from canary builds by @kenodegard in https://github.com/conda/conda/pull/13555
  * [x] Refactor rollback tests, move `conda run` test, and refactor revisions test by @kenodegard in https://github.com/conda/conda/pull/13546
  * [x] Enable `conda rename` to not throw a `TypeError` when conda is not activated by @beeankha in https://github.com/conda/conda/pull/13565
  * [x] Refactor pip interoperability tests by @kenodegard in https://github.com/conda/conda/pull/13537
  * [x] Updating Miniconda links by @travishathaway in https://github.com/conda/conda/pull/13572
  * [x] Channel IDs not parsed as strings by @travishathaway in https://github.com/conda/conda/pull/13543
  * [x] Ruff has moved some of the config values by @kenodegard in https://github.com/conda/conda/pull/13582
  * [ ] Optimize import time for `conda activate` by @mbargull in https://github.com/conda/conda/pull/13568
  * [x] Catch ZstdError in jlap/repodata.json.zst handling by @dholth in https://github.com/conda/conda/pull/13559
  * [x] change retry logic for 400 <= status < 500 by @dholth in https://github.com/conda/conda/pull/13576
  * [x] Pass traceback, not str, to exception formatter. by @dholth in https://github.com/conda/conda/pull/13532
  * [x] Add wildcard `conda remove` test by @zklaus in https://github.com/conda/conda/pull/13579
  * [x] Add `ISC`/`TCH`/`T10`/`FA` lints by @kenodegard in https://github.com/conda/conda/pull/13587
  * [x] Merge `24.1.x` back into `main` by @kenodegard in https://github.com/conda/conda/pull/13591
  * [x] Ignore `TYPE_CHECKING` imports in coverage reports by @kenodegard in https://github.com/conda/conda/pull/13597
  * [x] Merge `24.1.x` back into `main` by @kenodegard in https://github.com/conda/conda/pull/13606
  * [x] Update testing entrypoint deprecation by @kenodegard in https://github.com/conda/conda/pull/13613
  * [x] Update all actions including setup-miniconda to their latest version by @dbast in https://github.com/conda/conda/pull/13618
  * [x] gateways.subprocess: fix subprocess_call when stdin is bytes by @FFY00 in https://github.com/conda/conda/pull/13240
  * [x] Run macos tests on osx-64 and osx-arm64 runners by @dbast in https://github.com/conda/conda/pull/13617
  * [x] Remove `conda.export.handle_proxy_407` by @beeankha in https://github.com/conda/conda/pull/13629
  * [x] Add response string to repodata JSONDecodeError by @dholth in https://github.com/conda/conda/pull/13128
  * [x] Fix `conda env create` "`--subdir` / `--platform`" flag regression by @beeankha in https://github.com/conda/conda/pull/13632
  * [x] Report progress while installing from --revision by @jaimergp in https://github.com/conda/conda/pull/13611
  * [x] Fix auxlib.logz.stringify excess memory allocation by @mbargull in https://github.com/conda/conda/pull/13628
  * [x] Move `conda env export` to `conda export` by @beeankha in https://github.com/conda/conda/pull/13577
  * [x] Add ability for plugins to define settings by @travishathaway in https://github.com/conda/conda/pull/13554
  * [x] Remove `dev/linux`, `dev/macos`, `dev/windows` in favor of streamlined GH workflow by @kenodegard in https://github.com/conda/conda/pull/13162
  * [x] Fix archspec on windows by @isuruf in https://github.com/conda/conda/pull/13641
  * [x] Fixing broken link in settings plugin documentation by @travishathaway in https://github.com/conda/conda/pull/13662
  * [x] Check total_content_length is truthy before divide by @dholth in https://github.com/conda/conda/pull/13653
  * [x] Remove deprecations slated for 24.3 by @kenodegard in https://github.com/conda/conda/pull/13634
  * [x] Remove outdated badge. by @jezdez in https://github.com/conda/conda/pull/13666
  * [x] Fix the settings plugin hook example by @jjhelmus in https://github.com/conda/conda/pull/13667
  * [ ] Upload a release archive during release. by @jezdez in https://github.com/conda/conda/pull/13663
  * [x] Fix canary builds by @jezdez in https://github.com/conda/conda/pull/13669
  * [x] Add `boltons` to `requirements.txt` file for conda docs by @beeankha in https://github.com/conda/conda/pull/13679
  - [x] tested by @beeankha on Windows and MacOS osx 64
  - [x] tested by @jezdez on Windows and macOS on Apple Silicon
  </details>
#### Release week

- [x] #13683 (see [release process][process])
- [x] [Publish release][releases] https://github.com/conda/conda/releases/tag/24.3.0
- [x] [Merge `24.3.x` back into `main`](https://github.com/conda/conda/pull/13710)
- [x] Activate the `24.3.x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Feedstocks
	  - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/49
	  - [x] https://github.com/conda-forge/conda-feedstock/pull/232
	  
- [x] Hand off to the Anaconda packaging team

- [ ] Announce release
    - Blog Post
        - [x] conda.org https://github.com/conda-incubator/conda-dot-org/pull/185
    - Long form
        - [x] Create release [announcement draft](https://github.com/conda/communications) https://github.com/conda/communications/pull/27
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)

#### Hotfix-related PRs
  - https://github.com/AnacondaRecipes/repodata-hotfixes/pull/222
  - https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/685
