### ISSUE TITLE
Refactor conda to allow for configurable display backends

### ISSUE THREAD

**Issue by travishathaway** [conda/conda#13707]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

Conda currently has the `json` option which will trigger it to display only JSON to standard out. Otherwise it uses mostly print statements and loggers to print messages to the user in the normal flow of running commands. For this epic, we want to enable the addition of new display managers such as rich by refactoring conda.

This refactor will proceed in various steps and the issues linked here reflect those steps. By the end of the refactor we will be able to set a new configuration option, `output`, that will trigger the usage of a particular display backend. The current `json` option will become an alias for `output=json`.

### Individual components in conda needing a refactor

These are the individual components within conda itself that will need to be refactored to allow for new layouts and displays via the `output` configuration variable:

- [ ] Refactor error handler to allow for configurable `ouput` backend
- [ ] Refactor "Spinner" and "ProgressBar" to allow for configurable `output` backend
- [ ] Refactor confirmation to allow for a configurable `output` backend
- [ ] Refactor "update", "package plan" and "environment activation" messages to allow for configurable `output` backend
- [ ] Refactor "verification" step to allow for configurable `output` backend

These components are primarily used within `create`, `update` and `install`. As we go through these, we may want to combine multiple tasks into a single pull request. But, this separation should be a good starting point that will keep pull request size manageable and easier to review.

### Commands in conda needing to be refactored

If the above refactor has been performed correctly, then the refactor for many of the commands listed below should require none or a very small amount of work. The commands requiring the most work here will be ones such as `config` or `info` which rely heavily on print statements contained within their own modules.

This list serves as both a check list to make sure everything has been covered and as a starting point for issues for commands requiring a more in depth refactor effort.

- [ ] Refactor `create`, `update` and `install` commands to allow for a configurable `output` backend
- [ ] #13692
- [ ] Refactor `config` command to allow for a configurable `output` backend
- [ ] Refactor `compare` command to allow for a configurable `output` backend
- [ ] Refactor `list` command to allow for a configurable `output` backend
- [ ] Refactor `notices` command to allow for a configurable `output` backend
- [ ] Refactor `remove` command to allow for a configurable `output` backend
- [ ] Refactor `search` command to allow for a configurable `output` backend

Missing from this list are the `package` and `run` commands.  The prior is marked as "experimental" and can be skipped while the latter passes out directly from the commands it runs, so there is little need to refactor to accommodate a configurable `output`.

**Comment by jaimergp** [comment]
This is an excellent approach to this otherwise overwhelming task! Thanks for putting it together. My two cents / food-for-thought:

* What about verbosity levels? Configurable per-backend or global?
* What about quiet vs (non-)interactive? Current stdout output can be modified to remove progress bars and / or hide some messages depending on whether `--quiet` is passed, or if `sys.stdin.isatty()` is true.
* Can / should several outputs be used at the same time? e.g. normal, human-readable output to stdout, but also a json blob to a file path, and maybe extra verbose logging to a log file.
* `logging` usually reports to stderr (but we have some exceptions with stdout logger handlers T_T), which is usually intertwined with stdout. We need to think about how this would affect a rich output, because it might break UI. I'm sure they have good handlers though, but just another aspect of the problem to consider: output streams 😬

**Comment by jezdez** [comment]
> For example, the --json flag will resolve to the following reporters setting:

I think that's a design problem, we shouldn't use the config system as an ad-hoc plugin system, it's easy to add more into condarc I understand, but plugin already have a way to register new backends, via pluggy, we don't need a parallel system that goes through the config.

**Comment by jezdez** [comment]
> This is an excellent approach to this otherwise overwhelming task! Thanks for putting it together. My two cents / food-for-thought:
> 
> * What about verbosity levels? Configurable per-backend or global?
> * What about quiet vs (non-)interactive? Current stdout output can be modified to remove progress bars and / or hide some messages depending on whether `--quiet` is passed, or if `sys.stdin.isatty()` is true.
> * Can / should several outputs be used at the same time? e.g. normal, human-readable output to stdout, but also a json blob to a file path, and maybe extra verbose logging to a log file.
> * `logging` usually reports to stderr (but we have some exceptions with stdout logger handlers T_T), which is usually intertwined with stdout. We need to think about how this would affect a rich output, because it might break UI. I'm sure they have good handlers though, but just another aspect of the problem to consider: output streams 😬

Each reporter backend can take command/config options into account, using the context object. There is no need to add a meta-system to compose reporters ad-hoc.

**Comment by jezdez** [comment]
There is some overlap of the phase two items #13708 and #13777 to #14436 I just opened.
