### ISSUE TITLE
Release 24.4.x

### ISSUE THREAD

**Issue by jezdez** [conda/conda#13844]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

Placeholder for `conda 24.4.x` release.

| Pilot | @jezdez |
|---|---|
| Co-pilot | @beeankha |

### Tasks

[milestone]: https://github.com/conda/conda/milestone/71
[process]: https://github.com/conda/conda/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda/releases
[main]: https://github.com/AnacondaRecipes/conda-feedstock
[conda-forge]: https://github.com/conda-forge/conda-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda/

#### The week before release week

- [x] Create release branch (named `24.4.x`)
- [x] Ensure release candidates are being successfully built (see `conda-canary/label/rc-conda-24.4.x`)
- [x] [Complete outstanding PRs][milestone]
- [x] Test release candidates
    

#### Release week

- [x] https://github.com/conda/conda/pull/13847
- [x] https://github.com/conda/conda/releases/tag/24.4.0
- [x] https://github.com/conda/conda/pull/13871
- [x] Activate the `24.4.x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/50
    - [x] https://github.com/conda-forge/conda-feedstock/pull/234
    
- [x] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [ ] conda.org (link to pull request)
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)

**Comment by jezdez** [comment]
Closing as done. Update for weblog will come as part of the May release.
