### ISSUE TITLE
Rethink logging setup in conda and conda-build

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#13862]
### Checklist

- [X] I added a descriptive title
- [X] I searched open issues and couldn't find a duplicate

### What?

Rethink how we use `logging` in conda and conda-build.

### Why?

Conda and [conda-build](https://github.com/conda/conda-build/blob/main/conda_build/utils.py)’s logging setups are too complex. It has caused muddy logs in conda-build for years, it’s behind performance problems in conda, and floods the logs of the test suite in each run.

### User impact

- Application users won't suffer performance issues from excessive logging
- conda-build logs will look cleaner
- library users won't have to deal with the complexities built in conda's logging system

### Goals

- [ ] More idiomatic usage of `logging`, with few or no hacks.
- [ ] Rethink which logging handlers are needed
- [ ] Make sure the handlers are only enabled on the application layer
- [ ] Document and audit which levels should be used for which kind of messages

### Tasks

- [X] https://github.com/conda/conda/pull/13732
- [ ] https://github.com/conda/conda/issues/13541
- [ ] https://github.com/conda/conda/pull/13735
- [ ] https://github.com/conda/conda/issues/10556
- [ ] https://github.com/conda/conda/issues/7352 (reopen?)
- [ ] https://github.com/conda/conda-build/issues/4539 fixed by https://github.com/conda/conda-build/pull/4953 but I don't know why
- [ ] https://github.com/conda/conda-build/issues/683 (reopen?)
- [ ] https://github.com/conda/conda-build/issues/4846
- [ ] https://github.com/conda/conda-build/issues/2106
- [ ] https://github.com/conda/conda-build/issues/5274

### This epic is blocked by:

N/A

### This epic blocks:

Not a blocker, but it does interact with https://github.com/conda/conda/issues/13707
