### ISSUE TITLE
Ecosystem-wide test suite for solver conformance

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#13861]
### Checklist

- [X] I added a descriptive title
- [X] I searched open issues and couldn't find a duplicate

### What?

We propose creating a backend agnostic collection of test cases so different members of the ecosystem (e.g. conda’s own classic and libmamba solvers, but also external tools like micromamba and pixi) can assess their compliance to the underspecified solver behavior “expected” by the conda community.

### Why?

- The solver tests for conda are spread across different parts of the test suite as unit and integration tests. In many cases, they incur IO overheads that are not necessary and cause a general slowdown of the test suite completion and development feedback loop.
- The PyPI ecosystem has already set a precedent in this aspect (see https://github.com/zanieb/packse and https://github.com/pradyunsg/pip-resolver-benchmarks), and the conda ecosystem should also step up.

### User impact

More consistent behavior across solvers

### Goals

- [ ] Set a dedicated repository with solver test cases
- [ ] Integrate it in `conda/conda`
- [ ] Integrate it in `conda/conda-libmamba-solver`

### Tasks

- [ ] Create repository
- [ ] Design test case schema. Should be declarative and language agnostic (e.g. YAML or JSON)
- [ ] Create / consolidate test data (repodata, channels, etc) so there's no need to access live channels.
- [ ] Audit `conda/conda` for potential test cases
- [ ] Audit `conda/conda-libmamba-solver` for potential test cases
- [ ] Audit `mamba-org/mamba` for potential test cases
- [ ] Audit `mamba-org/rattler` for potential test cases
- [ ] Consolidate audits and write table of test cases with assumed inputs and expected outcomes
- [ ] Implement test cases

### This epic is blocked by:

N/A

### This epic blocks:

N/A

**Comment by jjerphan** [comment]
Thank you for starting the discussions, @jaimergp.

> Set a dedicated repository with solver test cases

Which GitHub organization should welcome this repository to you?

**Comment by jaimergp** [comment]
> Which GitHub organization should welcome this repository to you?

I was assuming we would start in conda-incubator.

**Comment by jjerphan** [comment]
List of known edge cases (feel free to edit this comment):
  - https://github.com/prefix-dev/pixi/issues/1708
  - https://github.com/conda-forge/openmpi-feedstock/issues/153
  - https://github.com/conda-forge/pocl-feedstock/issues/101
  - https://github.com/conda-forge/mpich-feedstock/issues/95
  - https://github.com/mamba-org/rattler/issues/684
  - Known hard environments to solve: https://github.com/conda-forge/rubinenv-feedstock/blob/main/recipe/meta.yaml
 - Submitted by Jaime: https://github.com/conda/conda-libmamba-solver/blob/155fe28acbd5cd2f57fd0259c5180fbf4daefa6f/tests/test_performance.py#L131
 - Submitted by Jaime: https://github.com/conda/conda-libmamba-solver/blob/main/tests/test_solver_differences.py
 - https://github.com/mamba-org/resolvo/pull/61/files#diff-75b7e1b2ff6f03636607e715f060aabb96639be642130ad9f4128b1cb3614377R1399-R1433

**Comment by jjerphan** [comment]
> Design test case schema. Should be declarative and language agnostic (e.g. YAML or JSON)

Would conda environment YAML specifications be sufficient?

**Comment by jaimergp** [comment]
I'm afraid that's only one possible input. I was picturing a schema where we can express things like:

- Input packages:
  - List of MatchSpecs
  - Installed packages
  - History
  - Aggressive updates
  - Pins
  - Non-manageable dependencies
- Action type (install/update)
- Solver flags (no-deps, only-deps, update-all, freeze-installed)
- Channels and priorities
- Subdirs
- Expected list of records (fully resolved environment; aka lockfile contents)

**Comment by jjerphan** [comment]
Thank you for those pieces of information.

For full disclosure and as discussed with @zklaus, I am interested in this PR being resolved, but I am leaving Klaus resolve it since he is assigned to it.

**Comment by jaimergp** [comment]
@zklaus has started a repo with some prototypes and pytest plugins at https://github.com/zklaus/pytest-conda-solvers.
