### ISSUE TITLE
Improve PyPI interoperability in conda env

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#13863]
### Checklist

- [X] I added a descriptive title
- [X] I searched open issues and couldn't find a duplicate

### What?

Improve PyPI interoperability in conda and conda env

### Why?

Many conda users want to still use PyPI packages in their environments. However, the user experience for these users can be much improved.

### User impact

Conda users will have a better experience when using PyPI packages. Fewer conda environments will be broken.

### Goals

- [ ] Implement a conda subcommand that allows to interact with `pip` in a safer way. This tool will also protect the environment from PyPI tooling changes. Prototype at https://github.com/jaimergp/conda-pip.
- [ ] Allow `conda env` to use this tool instead of the regular `pip` subcommand.

### Tasks

- [ ] All open issues in https://github.com/jaimergp/conda-pip
- [ ] https://github.com/conda/conda/issues/13833

**Comment by jezdez** [comment]
Updated the epic to reflect current status: removed closed conda/ceps#111 from blockers, updated Phase 0 target to 26.5 per accelerated roadmap. All linked PRs and issues are current.
