### ISSUE TITLE
Create deb and rpm packages with each conda release

### ISSUE THREAD

**Issue by marcoesters** [conda/conda#13896]
### Checklist

- [X] I added a descriptive title
- [X] I searched open issues and couldn't find a duplicate

### What?

Anaconda produces deb and rpm packages with each conda release. They are currently available in the following repositories:

* deb: https://repo.anaconda.com/pkgs/misc/debrepo/
* rpm: https://repo.anaconda.com/pkgs/misc/rpmrepo/

This is currently accomplished by installing `conda` into a new environment and packaging the directory into a deb and an rpm package. These packages are then indexed and uploaded to the repositories mentioned above.

These repositories are maintained and controlled by Anaconda. `conda` is, however, an open-source project and should thus be the entity creating these packages.

### Why?

The current deb and rpm releases for conda are built in a private repository by Anaconda. `conda`, however, is an open source product and should thus be the entity producing these artifacts and managing the repositories.

Integrating this process into the release process ensures that these package formats are available with each `conda` release. This can potentially be expanded to other package formats.

### User impact

`conda` gains control over all conda-related artifacts. This consolidates the codebase and facilitates bug reports. It also provides the opportunity to build other package formats with a new repository.

### Goals

* Create a repository for deb and rpm packages owned and controlled by `conda`.
* Incorporate the generation of these packages into the release process.

### Tasks

- [ ] Create repositories on a conda-owned domain for deb and rpm packages
- [ ] Generate a GPG key to sign the packages
- [ ] Create conda and upload conda packages with each release
- [ ] Create workflow to build deb and rpm packages on release and upload to repository

**Comment by maurerle** [comment]
Hi, is there anything one can do to get the ball rolling with this?

**Comment by danyeaw** [comment]
Hi @maurerle - this isn't one of the priorities that the core team is working on at the moment. However, if you would like to work on creating a GitHub Actions workflow that builds deb and rpms, that would get us closer to the overall solution.

**Comment by janxkoci** [comment]
As far as I know, deb & rpm packages require sudo/root permissions to install. This defeats the whole (or the main) point of conda for me.

Also, the current installation script runs everywhere - what's the benefit of distro-specific packages? All I see is extra maintenance burden..

**Comment by maurerle** [comment]
@janxkoci on a multi-user HPC system, it would be good if there is a multi user installation which updates automatically through unattended-updates.
This is not possible if every user downloads its own copy to wherever they want.
Keeping track of installed programs and their location is also much easier with a package manager installation.

Most of this is fine using pypi and python3-venv, but switching python versions requires conda (or uv)

**Comment by janxkoci** [comment]
@maurerle Actually, we currently have a system-wide installation of conda on one HPC at our department, which is updated by admin and users are allowed to create their personal environments. You don't need deb/rpm packages for this (we use miniforge, but it can be done with any of the current installers).

PS: We don't actually update packages "whenever", because that can break reproducibility and user's scripts (I've seen many times when packages changed flags and the same code no longer worked during a course just a year later). Any updates to the shared environments are upon request and after consideration. Users are free to update their personal environments as they please, of course.

PPS: If you just want to update conda itself regularly, the admin could just set up a cron job for that. I've seen such updates break stuff in the past, but many years ago, I think it should be much safer these days, as conda got significantly more robust.

**Comment by janxkoci** [comment]
Just FYI I've found a tutorial that describes the multi-user conda installation similar to what we use at our HPC: https://ubinfie.github.io/2024/04/02/shared-conda-tutorial.html

Can be an interesting alternative to DEB/RPM packages for users like @maurerle
