### ISSUE TITLE
Release 24.7.x

### ISSUE THREAD

**Issue by beeankha** [conda/conda#13995]
### Summary

Placeholder for `conda 24.7.x` release.

| Pilot | @kenodegard  |
|---|---|
| Co-pilot | @ForgottenProgramme  |

### Tasks

[milestone]: https://github.com/conda/conda/milestone/70
[process]: https://github.com/conda/conda/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda/releases
[main]: https://github.com/AnacondaRecipes/conda-feedstock
[conda-forge]: https://github.com/conda-forge/conda-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda/

<details>  
<summary><h4>The week before release week</h4></summary>

- [x] [Create release branch (named `24.7.x`)](https://github.com/conda/conda/tree/24.7.x)
- [x] [Ensure release candidates are being successfully built (see `conda-canary/label/rc-conda-24.7.x`)](https://anaconda.org/conda-canary/conda/files?channel=rc-conda-24.7.x)
- [x] [Complete outstanding PRs](https://github.com/conda/conda/milestone/70)
- [x] Verify release candidates (by [name] on [system(s)], ...)
    - by @kenodegard on conda.org:
        - [x] #13889
        - [x] #13909
	    - [x] #13935
	    - [x] #13950 & https://github.com/conda/conda/pull/14046/commits/a78318a28b44588a1d28cbdc2242d4380d35cd18
        - [x] #13954
        - [x] #13984
        - [x] #13970
        - [x] #12856 & https://github.com/conda/conda/pull/14046/commits/241912557ba30c25632048ed646a0c1b4afa963b
    - by @kenodegard on macOS:
        - [x] #13877
	    - [x] #13649
	    - [x] #13946
	    - [x] #13941
	    - [x] #13931
	    - [x] #13937
	    - [x] #13936
	    - [x] #13960
	    - [x] #13940
        - [x] #13939
        - [x] #13735 & https://github.com/conda/conda/pull/14046/commits/88f56e7554575da2d7e43c13ff2b8561fcb749a8
        - [x] #13943
        - [x] #14004
		- [x] #13972
		- [x] #13817
		- [x] #14034
		- [x] #13969
		- [x] #13846
		- [x] #14044
		- [x] #13962
	- by @kenodegard on Windows:
	    - [x] #13961
	    - [x] #13975
	- [ ] #13963
	- [ ] #13987
	- [ ] #14003
	- [ ] #14030

</details>

<details open>  
<summary><h4>Release week</h4></summary>

- [x] Create release PR (see [release process](https://github.com/conda/conda/blob/main/RELEASE.md)) https://github.com/conda/conda/pull/14046
- [x] [Publish release](https://github.com/conda/conda/releases) https://github.com/conda/conda/releases/tag/24.7.0
- [x] https://github.com/conda/conda/pull/14061
- [x] Activate the `24.7.x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/52
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/53
    - [x] https://github.com/conda-forge/conda-feedstock/pull/238
    
- [x] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [x] https://github.com/conda-incubator/conda-dot-org/pull/194
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)

</details>

<details open>
<summary><h4>Hotfix 24.7.1</h4></summary>

- [x] https://github.com/conda/conda/pull/14065
- [x] Create release PR (see [release process][process]) https://github.com/conda/conda/pull/14075
- [x] [Publish release][releases] https://github.com/conda/conda/releases/tag/24.7.1
- [x] https://github.com/conda/conda/pull/14076
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/54
    - [x] https://github.com/conda-forge/conda-feedstock/pull/239
- [x] Hand off to the Anaconda packaging team

</details>

**Comment by snnn** [comment]
Will the "vs2015_runtime" package be updated to a newer version? The current one is incompatible with binaries built with VS 2022 17.10.

**Comment by kenodegard** [comment]
@snnn unfortunately the conda release does not correlate or guarantee updates to other packages.

That said have you tried `conda-forge::vc14_runtime`? Otherwise requests for packages to be updated on the `defaults` channel should be opened at https://github.com/ContinuumIO/anaconda-issues.

**Comment by jakirkham** [comment]
JFYI have seen some issues with re-rendering using `conda-smithy`, which go away when using `conda-build` version `24.5.1` and appear when using `conda-build` version `24.7.1`. No other changes needed

This appears related to how conditionally defined Jinja variables are being handled. Think this may be coming from changes in the rendering logic in conda-build, but have not yet narrowed down exactly the cause

More details in issue: https://github.com/conda-forge/conda-smithy/issues/2011

**Comment by jakirkham** [comment]
> JFYI have seen some issues with re-rendering using `conda-smithy`, which go away when using `conda-build` version `24.5.1` and appear when using `conda-build` version `24.7.1`. No other changes needed
> 
> This appears related to how conditionally defined Jinja variables are being handled. Think this may be coming from changes in the rendering logic in conda-build, but have not yet narrowed down exactly the cause
> 
> More details in issue: [conda-forge/conda-smithy#2011](https://github.com/conda-forge/conda-smithy/issues/2011)

Looks like this would be addressed in PR: https://github.com/conda/conda-build/pull/5458

**Comment by h-vetinari** [comment]
> JFYI have seen some issues with re-rendering using `conda-smithy`, which go away when using `conda-build` version `24.5.1` and appear when using `conda-build` version `24.7.1`. No other changes needed

You're commenting on the conda (not conda-build) tracker. Better to move this to https://github.com/conda/conda-build/issues/5381.

**Comment by jakirkham** [comment]
Ah sorry 😞 

Thanks for copying my comment to the right place 🙏

**Comment by jezdez** [comment]
Hey all, with the upcoming 24.9.x release, this is good to close.
