### ISSUE TITLE
Channel handling improvements

### ISSUE THREAD

**Issue by jezdez** [conda/conda#14217]
### Checklist

- [X] I added a descriptive title
- [X] I searched open issues and couldn't find a duplicate

### What?

Following feedback from end users around concerns related to channels with terms of services and other legal restrictions, we can improve conde to handle channel management a little better by default. The goal of this initiative is to work on a consistent resolution to user experience issues as well as overcoming some tech debt in conda's code base.

### Why?

Various stakeholders in the conda ecosystem have reported concerns about the pre-configuration of conda to favor channels from Anaconda Inc. While distributions like [miniforge](https://github.com/conda-forge/miniforge) come pre-configured for conda-forge, conda itself hard-codes Anaconda Inc channels within its code base, due to the way conda was incubated historically.

Conda has been a full Open-Source project with a permissive license and governed by [a steering council per its governance policy](https://github.com/conda/governance) for a while now. As such, this pre-configuration has detrimental effects on the trust and reputation of the conda OSS project among conda users that aren't Anaconda Inc customers.

### User impact

Less confusing way of handling channels, no accidental use of an unwanted channel, conda is more agnostic to how channels are run etc.

### Goals

- user focus, reduce legal risks for end users
- overcome historic decisions on how conda is configured, pay down tech-debt

### Tasks

- [ ] https://github.com/conda/conda/issues/12356
- [ ] https://github.com/conda/conda/issues/14178
- [ ] https://github.com/conda/conda/issues/14176

### This epic is blocked by:

- [ ] <dependency epic or issue>

### This epic blocks:

- [ ] <dependency epic or issue>

**Comment by jezdez** [comment]
@jaimergp I've started this epic, in case you see other tickets, feel free to mention them here

**Comment by SylvainCorlay** [comment]
As the conda project transitions towards a more open governance, it makes perfect sense for it to be developed with **vendor agnosticism** in mind, and I salute @jezdez for opening this issue. As pointed out in this issue, the fact that Anaconda channels are hardcoded as the default channels in the codebase is one instance in which the project is currently not vendor agnostic, although it could easily be overriden (like seen in miniforge).

Additionally, it would be beneficial to update the project's **readme** and **documentation** to:
 - clearly state that the miniconda and anaconda installers advertised in the documentation may incur costs. (I think it is perfectly fine to advertise these installers, and to mention that the associated costs come with e.g. commercial support or other benefits).
 - maybe mention that there are other significant distributions like conda-forge, for which installers can be found at https://conda-forge.org/download/.

Another aspect where the conda codebase is not currently vendor agnostic is the hard-coded root keys for the **conda content trust protocol**. Root keys (similar to root certificates for SSL) should be configurable to allow projects such as conda-forge to set up their own keys and generate package signatures. This limitation could hinder conda-forge from implementing essential software supply chain security features, which are progressively becoming regulatory requirements.

**Comment by MikaelUmaN** [comment]
Hello. Please let me know if you would rather see a bug report for this, but I am experiencing an issue whereby `https//repo.anaconda.com/pkgs/main/linux-64` is always added back during `conda install` regardless of user instructions.

For example:

```dockerfile
# Create basic root python environment with proxied public channels.
RUN conda config --system --remove channels defaults && \
    conda config --system --add channels https://my-repo.abc.se/repository/conda-forge && \
    conda config --set channel_priority strict && \
    conda clean --all && \
    conda install curl && \
    conda clean --all && \
    conda init bash
```

This does not work, but results in:

```bash
root@06140b801505:/#  conda install curl
Channels:
 - https://inf-repo-02.lynxhedge.se/repository/conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/linux-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

'https//repo.anaconda.com/pkgs/main/linux-64'
```

which is frustrating.

When looking at the channels existing everything seems fine:

```bash
root@06140b801505:/# conda config --show channels
channels:
  - https://my-repo.abc.se/repository/conda-forge
```

**Comment by leagueofsoups** [comment]
@MikaelUmaN 
Hi! I had a similar problem, but I deploy the environment from a file. 
https://github.com/conda/conda/blob/d87c1c804841a8bffb01b585da196259b1ab3a91/conda/env/installers/conda.py#L21-L22
```
name: base
channels:
  - https://you.private.repo/path
  - nodefaults
dependencies:
  - h2=4.1.0=pyhd8ed1ab_0
prefix: /home/app/miniconda3/envs/debug
```
conda env create  -f /tmp/environment.yml -n debug -v

**Comment by jaimergp** [comment]
@MikaelUmaN , you are facing https://github.com/conda/conda/issues/12356. Your `--remove` workaround needs to happen _after_ you add the other channel. First append, then remove defaults.

**Comment by jaimergp** [comment]
xref https://github.com/conda-incubator/setup-miniconda/pull/364

**Comment by ruben-arts** [comment]
Hey could you explain how to avoid adding `defaults` to my config when using `conda config --add channels conda-forge`?

I currently still get `defaults` in my `.condarc`

I've installed `conda` from `conda-forge`.

```
➜ cat ~/.condarc

➜ conda config --add channels conda-forge
/Users/user/.pixi/envs/conda/lib/python3.13/site-packages/conda/base/context.py:211: FutureWarning: Adding 'defaults' to channel list implicitly is deprecated and will be removed in 25.9. 

To remove this warning, please choose a default channel explicitly with conda's regular configuration system, e.g. by adding 'defaults' to the list of channels:

  conda config --add channels defaults

For more information see https://docs.conda.io/projects/conda/en/stable/user-guide/configuration/use-condarc.html

  deprecated.topic(

➜ cat ~/.condarc                         
channels:
  - conda-forge
  - defaults

```

This TODO list gives me the impression this shouldn't happen anymore.
