### ISSUE TITLE
Release 24.11.x

### ISSUE THREAD

**Issue by beeankha** [conda/conda#14364]
### Summary

Placeholder for `conda 24.11.x` release.

| Pilot | @ForgottenProgramme  |
|---|---|
| Co-pilot | @travishathaway   |
| Jumpseat | @kenodegard   |

### Tasks

[milestone]: https://github.com/conda/conda/milestone/72
[process]: https://github.com/conda/conda/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda/releases
[main]: https://github.com/AnacondaRecipes/conda-feedstock
[conda-forge]: https://github.com/conda-forge/conda-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda/

<details>
<summary><h4>The week before release week</h4></summary>

- [x] Create release branch (named [`24.11.x`](https://github.com/conda/conda/tree/24.11.x))
- [x] Ensure release candidates are being successfully built (see [`conda-canary/label/rc-conda-24.11.x`](https://anaconda.org/conda-canary/repo/files?type=any&label=rc-conda-24.11.x))
- [x] [Complete outstanding PRs][milestone]
- [x] Test release candidates
    

Tested by @ForgottenProgramme on MacOS, @beeankha on Windows
Deprecation:
- [x] https://github.com/conda/conda/pull/14338
- [x] https://github.com/conda/conda/pull/14368
- [x] https://github.com/conda/conda/pull/14277

Bug Fixes:
- [x] https://github.com/conda/conda/pull/13784
- [x] https://github.com/conda/conda/pull/14271
- [x] https://github.com/conda/conda/pull/14359
- [x] https://github.com/conda/conda/pull/14375
- [x] https://github.com/conda/conda/pull/14323

Enhancements:
- [x] https://github.com/conda/conda/pull/14245
- [x] https://github.com/conda/conda/pull/14256
- [x] https://github.com/conda/conda/pull/14382
- [x] https://github.com/conda/conda/pull/14325

</details>

<details>
<summary><h4>Release week</h4></summary>

- [x] Create release PR (see [release process][process]) https://github.com/conda/conda/pull/14396
- [x] [Publish release][releases] https://github.com/conda/conda/releases/tag/24.11.0
- [x] https://github.com/conda/conda/pull/14410
- [x] Activate the `24.11.x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/59
    - [x] https://github.com/conda-forge/conda-feedstock/pull/243
    
- [x] Hand off to the Anaconda packaging team
- [x] Announce release
    - Blog Post (optional)
        - [x] https://github.com/conda/conda-dot-org/pull/231
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)

</details>

<details>
<summary><h4>Patch release 24.11.1</h4></summary>

- [x] https://github.com/conda/conda/pull/14431
- [x] Create release PR (see [release process][process]) https://github.com/conda/conda/pull/14434
- [x] https://github.com/conda/conda/pull/14437
- [x] [Publish release][releases] https://github.com/conda/conda/releases/tag/24.11.1
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/60
    - [x] https://github.com/conda-forge/conda-feedstock/pull/247
    
- [x] Hand off to the Anaconda packaging team

</details>

<details>
<summary><h4>Patch 24.11.2</h4></summary>

- [x] https://github.com/conda/conda/pull/14454
- [x] https://github.com/conda/conda/pull/14455
- [x] Create release PR (see [release process][process]) https://github.com/conda/conda/pull/14456
- [x] [Publish release][releases] https://github.com/conda/conda/releases/tag/24.11.2
- [x] https://github.com/conda/conda/pull/14437
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/62
    - [x] https://github.com/conda-forge/conda-feedstock/pull/248
- [x] Hand off to the Anaconda packaging team

</details>

<details>
<summary><h4>Patch 24.11.3</h4></summary>

- [x] https://github.com/conda/conda/pull/14468
- [x] Create release PR (see [release process][process]) https://github.com/conda/conda/pull/14473
- [x] [Publish release][releases] https://github.com/conda/conda/releases/tag/24.11.3
- [x] https://github.com/conda/conda/pull/14437
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-feedstock/pull/63
    - [x] https://github.com/conda-forge/conda-feedstock/pull/254
- [x] Hand off to the Anaconda packaging team

</details>
