### ISSUE TITLE
Review suppressed CLI arguments

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#14420]
### Checklist

- [x] I added a descriptive title
- [x] I searched open issues and couldn't find a duplicate

### What?

A number of CLI arguments are marked as suppressed. Review all of them and either deprecate them or re-expose the argument. IOW nothing should be suppressed.

### Why?

- [ ] https://github.com/conda/conda/issues/14418#issuecomment-2511905123

### User impact

Remove confusion over undocumented CLI arguments.

### Goals

- [ ] Either deprecate or re-expose all suppressed CLI arguments

### Tasks

- [ ] Review `conda config --force`
- [ ] Review `conda init --dev`
- [ ] Review `conda init --install`
- [ ] Review `conda info --offline`
- [ ] Review `conda info --license`
- [ ] Review `conda info --root`
- [ ] Review `conda search MATCH_SPEC`
- [ ] Review `conda search --canonical`
- [ ] Review `conda search --full-name`
- [ ] Review `conda search --names-only`
- [ ] Review `conda search --outdated`
- [ ] Review `conda search --spec`
- [ ] Review `conda search --reverse-dependency`
- [ ] Review `--json`
- [ ] Review `--force-pscheck`
- [ ] Review `--no-show-channel-urls`
- [ ] Review `--channel-priority`
- [ ] Review `--prune`
- [ ] Review `--force`
- [ ] Review `--shortcuts`
- [ ] Review `--unknown`
- [ ] Review `--debug`
- [ ] Review `--trace`

### This epic is blocked by:

- [ ] <dependency epic or issue>

### This epic blocks:

- [ ] <dependency epic or issue>

**Comment by prady0t** [comment]
Hi! I would love to help out here. Let me go through each command.
