### ISSUE TITLE
add a `conda doctor` command

### ISSUE THREAD

**Issue by pzwang** [conda/conda#474]
Per discussion on Flowdock, having a conda equivalent of `brew doctor` to display detailed information, including:
- environment variables like PYTHONPATH, LD_LIBRARY_PATH, etc.
- compiler-related information: what C, C++, FORTRAN compilers are on the system. Any persistent environment variables affection various compilers on various systems
- system & OS information
- Python information
- common framework configs: Numpy, Qt, wx, etc. all have library-specific information that can be dumped.  For Qt, especially important to note whether Pyside or pyqt is being used
- Any Windows-specific things that could affect Anaconda and conda?  Like roaming profiles, etc.?  (ping @tpn)

---

Edit by @kalefranz

As discussed below, what at @pzwang is enumerating as options is already covered by `conda info`.  However, the idea of having `conda doctor` inspect environments is still valid, and further discussion enumerates what those checks could/should actually be.

Compiled from discussion below, a running list of what *should* be checked by `conda doctor`:

* SAT satisfiability of an environment
* sha256 and size of every path in the environment (or alternately if path is missing)
* the existence of non-tracked files in an environment
* overlapping paths in `conda-meta` for an environment
* if pip has replaced entire packages and `conda-meta` is out-of-date

---

Edited in 2022

### Tasks

- [x] Write a spike that summarizes all of the concerns brought up in this issue and then proposes exactly how this new command would function. (timebox: 3 days)
  - [x] Should this command be a plugin? Why or why not?
  - [x] Who will use this command?
  - [x] What will the user interface look like? (see this CEP for inspiration: https://github.com/conda-incubator/ceps/blob/main/cep-6.md)
  - [x] Why will this be useful?

**Comment by kalefranz** [comment]
As Ilan said, most of the original information as requested by Peter is in `conda info --all`.  So the original feature request is outdated.

However, a `conda doctor` command is still needed to check (1) the integrity of environments, and (2) permissions for a target environment, envs directories, packages caches, etc.

**Comment by kalefranz** [comment]
From https://github.com/conda/conda/issues/4208#issuecomment-270997227

> A few possible sanity checks:
> 1. Are the packages satisifed (according to the solver).  IIRC, this happens anytime there are package changes in an environment.
> 2. Are all the files present in the environment? This would verify that all files that are claimed to be in the environment, are actually present.  Mapping os.path.exists on the files list in the conda-meta json files accomplishes this.  Are files that are supposed to be hardlinked/symlinked actually hardlinks/symlinks?
> 3. Check file permissions.
> 
> What other checks would determine the health of an environment?

**Comment by goanpeca** [comment]
Is the environment liste on environments.txt ?

**Comment by mingwandroid** [comment]
That all files not marked for prefix replacement still have the same checksum as they are meant to have and that those that are marked for prefix replacement have the same checksum if you replace the prefix with /opt/anaconda1anaconda2anaconda3 (for text files).

**Comment by tyoc213** [comment]
Any plans to implement this?

**Comment by TheGreatMarkus** [comment]
I'd also be interested in seeing this

**Comment by qodrinzo** [comment]
+1 for this feature

**Comment by tyoc213** [comment]
I guess there are other issues but will be nice to 

https://github.com/conda/conda/issues/9367
