### ISSUE TITLE
Enhance conda's interoperability with pip

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#7053]
> As a conda user who also uses pip on the same environment, I want conda to be smart about interacting with what pip has installed, so that I don't have clobbering, double installs, and other bad interactions.

The solver is going to have to be able to interact with package units that are not conda packages.  Right now we effectively have *two* ways to describe packages: (1) dists, and (2) package records.  Since @mcg1969 and I started with conda 4.0 solver work, we've always known dists were dangerous and undesirable, since they are derived from the package tarball filename rather than the metadata contained in the package.  Effectively, there's a duplication of information that can potentially become disjoint, and we agree that the single source of truth is the information contained in the package metadata, so mixing and matching information from dists and records can lead to unambiguous situations.

As we endeavor to introduce new package types here, i.e. python packages in a prefix that have not been installed by conda, we need to first reduce the dangerous ambiguity and complexity in the solver by finally chopping out dist usage.  All packages will then be represented by appropriate records.

- [x] Remove dist from conda/resolve.py https://github.com/conda/conda/issues/6979
- [x] Remove dist from remainder of project. #7086

We need to introduce a new package type for python packages in a prefix that have not been conda installed, and then teach PrefixData how to populate records representing those packages and match queries against those packages.

- [x] Add pip shadow packages into PrefixData #7087
- [x] Teach PrefixData to override (and either correct, or remove) information in the conda-meta directory when it can be determined that another package manager has mutated the python environment and caused the conda-meta information to be incorrect.

When a prefix has non-conda installed python packages in it, we need to teach the solver that those should not be scheduled for changes or updates, but that they can still satisfy dependencies of other packages.

- [x] Teach conda/resolve.py to freeze immutable pip shadow packages 
- [x] For immutable pip packages that create unsatisfiable situations with a user request, make sure we 
        have solid error messaging
- [ ] Determine where we can translate differences between conda and pip versions to the conda scheme, and determine and implement how we handle the cases where those versions can't be converted.

Anaconda and conda-forge are known to have certain package name mismatches, but we generally eventually converge to the same point.  That's not going to be possible for PyPI.  We'll need some type of universal mapping of package name equivalencies that sits at a higher level than information relevant to an individual channel, or even an individual grouping of channels (e.g. repo.anaconda.com and conda.anaconda.org).

- [ ] Universal package name map

Optionally, if there is sufficient metadata to be able to fully remove the non-conda installed python package (sometimes there is, and sometimes there isn't), we can allow conda to update that package.  Advantages would be that users can potentially bring their environments into satisfiability, they don't have to be burdened to switch back to pip to uninstall a package before their environment can be fully updated, and they can have substituted potentially problematic python packages that contain compiled code for conda packages that are able to properly rely on dependencies that are lower-level than python.

- [x] Teach conda/resolve.py to be able to update mutable pip shadow packages
- [x] Teach UnlinkLinkTransaction to uninstall mutable pip shadow packages

- [ ] Determine if impact on performance is acceptable, or if we have hotspots we need to smooth over
- [ ] Look into handling `easy_install.pth` and `.pth` files in general
- [ ] Figure out strategies for pip-installed namespace packages

**Comment by kalefranz** [comment]
- [ ] Convert .dist-info metadata to conda PrefixRecord #7428
- [ ] Convert .egg-info directory to conda PrefixRecord #7588
- [ ] Convert .egg-info file to conda PrefixRecord #7589
- [ ] Convert .egg-link file to conda PrefixRecord #7590
- [ ] Pull in improvements from namespaces PR for 4.6 #7591
- [ ] Compatibility shims for future releases #7592
- [ ] Hook new python package types into solver #7593

**Comment by kalefranz** [comment]
Besides the universal package name map, which following the namespace push may no longer be applicable, the bulk of this work landed in #7710.  Closing this issue now.

**Comment by sdvillal** [comment]
Congrats, this sounds magnificent.
