### ISSUE TITLE
Ecosystem namespace support

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#7429]
- [ ] Add a namespace field to MatchSpec #7430
- [ ] Make package exclusion key be namespace + package name #7431
- [ ] Dynamically add namespace to repodata based on dependency tree #7432
- [ ] Determine how to handle non-namespaced packages #7433
- [ ] Work through solver edge cases and test solver #7434
- [ ] Fix conda list after introduction of package namespace concept #7435
- [ ] Test history with MatchSpec changes from package namespace concept #7436
- [ ] Add conda version check to history entries in 4.3 and forward #7437

**Comment by dhirschfeld** [comment]
***xref:*** #6939

**Comment by dhirschfeld** [comment]
An interesting thread by @njsmith over at
https://discuss.python.org/t/structured-exchangeable-lock-file-format-requirements-txt-2-0/876/34

**Comment by kenodegard** [comment]
Since all 8 items in this epic are completed we will close this out.
