### ISSUE TITLE
Markers and system state package dependencies

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#7438]
- [x] Enhance MatchSpec to be conditionally applied #7439
- [x] Create virtual packages to allow solver to select on and fulfill system requirements #7440
- [x] Teach solver to use marker-enhanced MatchSpec. Test edge cases #7441
- [x] Test history with marker-enhanced MatchSpec #7442
- [x] Hook marker-enhanced MatchSpec into and test with noarch: python packages #7443

**Comment by kenodegard** [comment]
Closing this out since all 5 items have been completed.
