### ISSUE TITLE
 Solver improvements: meta issue

### ISSUE THREAD

**Issue by mbargull** [conda/conda#7700]
0. [x] Solver improvements: 0) Solver speedups in common.logic #7676
1. [x] Solver improvements: 1) use CryptoMiniSat as the default SAT solver #7694
2. [x] Solver improvements: 2) translate hotspots functions in common.logic into compiled code #7696
3. [x] Solver improvements: 3) store clauses in a more memory efficient way #7697
4. [x] Solver improvements: 4) make solver runs more deterministic #7698
5. [x] Solver improvements: 5) explore ways to invoke the SAT solver more incrementally #7699
6. [x] Solver improvements: 6) explore more creative and aggressive parameter space reduction (i.e. `get_reduced_index()`) #7809

Anyone, feel free to contribute to any of the above! 1) -- 4) shouldn't be too hard, if anyone wants to give those a shot!

**Comment by msarahan** [comment]
I have set up Airspeed Velocity for conda with some simple, very high level benchmarks.  See https://github.com/conda/conda-benchmarks for the code and https://conda.github.io/conda-benchmarks for results.

Note that each commit takes about 5 min to run.  It's going to take a very long time to fully populate this graph.  Still, I hope the benchmarking code is perhaps useful for evaluating the success of the efforts highlighted in the issue.

**Comment by abalter** [comment]
Is there any way to trade some disk storage for solver time by saving useful information in a local file?

**Comment by abalter** [comment]
Because there might be another interested person who doesn't really know what the solver does, I mean I totally understand, but just in case _someone else_ who _doesn't_ understand comes along and wants to participate in this discussion, would it be possible in a few brilliantly crafted sentences to summarize?

**Comment by mhlr** [comment]
Does somebody already have a profiler dump from of a long conda run?

**Comment by mhlr** [comment]
Here is a a profile of 3 minute run, just updating conda itself. It suggest that the real problem is not in the solver itself but in the setup of the solver problem namely

```
        1    0.000    0.000   99.452   99.452 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/solve.py:256(_collect_all_metadata)
        1    0.002    0.002   96.646   96.646 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/solve.py:641(_prepare)
        1    0.153    0.153   95.918   95.918 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/index.py:134(get_reduced_index)
     1054    0.038    0.000   85.232    0.081 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/index.py:174(query_all)
    56864    0.077    0.000   83.968    0.001 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py:91(query)
```
Another thing that jumps out is

```
        2    0.001    0.000   78.587   39.293 /home/dm/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py:33(create_connection)
       12   78.576    6.548   78.576    6.548 {method 'connect' of '_socket.socket' objects}
```

In contrast the actual solving seems to only take 36 seconds< 20% of the total time"

```
        1    0.014    0.014   35.720   35.720 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/solve.py:436(_run_sat)
```

```
In [7]: prf.sort_stats('cumtime').print_stats(100)                                                                                                                                                                                                                                                                                                                                                                                                                                             
Thu Jan 10 16:44:41 2019    conda.prof

         155294767 function calls (152786643 primitive calls) in 185.800 seconds

   Ordered by: cumulative time
   List reduced from 4812 to 100 due to restriction <100>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    480/1    0.012    0.000  188.127  188.127 {built-in method builtins.exec}
        1    0.000    0.000  188.127  188.127 /home/dm/anaconda3/bin/conda:3(<module>)
        1    0.000    0.000  188.122  188.122 /home/dm/anaconda3/lib/python3.6/site-packages/conda/cli/main.py:89(main)
        1    0.000    0.000  188.029  188.029 /home/dm/anaconda3/lib/python3.6/site-packages/conda/exceptions.py:1288(conda_exception_handler)
        1    0.000    0.000  188.029  188.029 /home/dm/anaconda3/lib/python3.6/site-packages/conda/exceptions.py:999(__call__)
        1    0.000    0.000  188.029  188.029 /home/dm/anaconda3/lib/python3.6/site-packages/conda/cli/main.py:67(_main)
        1    0.000    0.000  187.962  187.962 /home/dm/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py:76(do_call)
        1    0.000    0.000  187.745  187.745 /home/dm/anaconda3/lib/python3.6/site-packages/conda/cli/main_update.py:13(execute)
        1    0.000    0.000  187.743  187.743 /home/dm/anaconda3/lib/python3.6/site-packages/conda/cli/install.py:127(install)
        1    0.000    0.000  179.716  179.716 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/solve.py:78(solve_for_transaction)
        1    0.000    0.000  179.697  179.697 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/solve.py:116(solve_for_diff)
        1    0.000    0.000  164.109  164.109 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/solve.py:158(solve_final_state)
        1    0.000    0.000   99.452   99.452 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/solve.py:256(_collect_all_metadata)
        1    0.002    0.002   96.646   96.646 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/solve.py:641(_prepare)
        1    0.153    0.153   95.918   95.918 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/index.py:134(get_reduced_index)
     1054    0.038    0.000   85.232    0.081 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/index.py:174(query_all)
    56864    0.077    0.000   83.968    0.001 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py:91(query)
       16    0.000    0.000   83.573    5.223 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py:146(load)
       16    0.002    0.000   83.572    5.223 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py:170(_load)
       14    0.001    0.000   82.494    5.892 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py:406(fetch_repodata_remote_request)
       14    0.000    0.000   82.386    5.885 /home/dm/anaconda3/lib/python3.6/site-packages/requests/sessions.py:537(get)
       14    0.001    0.000   82.386    5.885 /home/dm/anaconda3/lib/python3.6/site-packages/requests/sessions.py:466(request)
       14    0.001    0.000   82.199    5.871 /home/dm/anaconda3/lib/python3.6/site-packages/requests/sessions.py:617(send)
       14    0.001    0.000   82.174    5.870 /home/dm/anaconda3/lib/python3.6/site-packages/requests/adapters.py:394(send)
       14    0.001    0.000   82.140    5.867 /home/dm/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py:446(urlopen)
       14    0.001    0.000   82.127    5.866 /home/dm/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py:319(_make_request)
       14    0.000    0.000   79.028    5.645 /home/dm/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py:831(_validate_conn)
        2    0.000    0.000   79.027   39.514 /home/dm/anaconda3/lib/python3.6/site-packages/urllib3/connection.py:299(connect)
        2    0.000    0.000   78.587   39.293 /home/dm/anaconda3/lib/python3.6/site-packages/urllib3/connection.py:145(_new_conn)
        2    0.001    0.000   78.587   39.293 /home/dm/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py:33(create_connection)
       12   78.576    6.548   78.576    6.548 {method 'connect' of '_socket.socket' objects}
  5710574    6.802    0.000   37.159    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/models/match_spec.py:223(match)
      9/7    0.021    0.002   36.225    5.175 /home/dm/anaconda3/lib/python3.6/site-packages/conda/common/io.py:82(decorated)
        1    0.014    0.014   35.720   35.720 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/solve.py:436(_run_sat)
1525086/1523882    1.371    0.000   32.753    0.000 {built-in method builtins.any}
        2    0.044    0.022   31.213   15.607 /home/dm/anaconda3/lib/python3.6/site-packages/conda/models/prefix_graph.py:32(__init__)
     6752    0.867    0.000   29.436    0.004 /home/dm/anaconda3/lib/python3.6/site-packages/conda/models/prefix_graph.py:40(<genexpr>)
  6175009    3.497    0.000   24.832    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/models/match_spec.py:237(_match_individual)
       13    0.025    0.002   23.916    1.840 /home/dm/anaconda3/lib/python3.6/site-packages/conda/common/logic.py:797(minimize)
        1    0.009    0.009   19.395   19.395 /home/dm/anaconda3/lib/python3.6/site-packages/conda/resolve.py:925(solve)
        1    0.000    0.000   15.752   15.752 /home/dm/anaconda3/lib/python3.6/site-packages/conda/resolve.py:773(get_conflicting_specs)
        1    0.000    0.000   15.587   15.587 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/solve.py:773(diff_for_unlink_link_precs)
66796/65440    0.194    0.000   13.762    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/common/logic.py:366(Eval_)
    49282    0.079    0.000   13.630    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/common/logic.py:404(Require)
        1    0.022    0.022   13.025   13.025 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/solve.py:338(_find_inconsistent_packages)
     1405    0.149    0.000   12.970    0.009 /home/dm/anaconda3/lib/python3.6/site-packages/conda/common/logic.py:700(LinearBound_)
     1400    5.553    0.004   12.790    0.009 /home/dm/anaconda3/lib/python3.6/site-packages/conda/common/logic.py:652(BDD_)
       49    0.000    0.000   12.733    0.260 /home/dm/anaconda3/lib/python3.6/site-packages/conda/common/logic.py:728(LinearBound)
        1    0.004    0.004   12.658   12.658 /home/dm/anaconda3/lib/python3.6/site-packages/conda/resolve.py:809(bad_installed)
        3    0.141    0.047   11.349    3.783 /home/dm/anaconda3/lib/python3.6/site-packages/conda/resolve.py:590(gen_clauses)
    63025    0.795    0.000   10.891    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/models/records.py:311(combined_depends)
7455739/7455334    3.061    0.000   10.860    0.000 {built-in method builtins.getattr}
  8220760    7.805    0.000   10.464    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py:403(__get__)
       69    0.001    0.000   10.195    0.148 /home/dm/anaconda3/lib/python3.6/site-packages/conda/common/logic.py:738(sat)
       69    0.720    0.010   10.192    0.148 /home/dm/anaconda3/lib/python3.6/site-packages/conda/common/logic.py:732(_run_sat)
        2    0.010    0.005   10.023    5.012 /home/dm/anaconda3/lib/python3.6/site-packages/conda/resolve.py:312(get_reduced_index)
       70    0.001    0.000    9.472    0.135 /home/dm/anaconda3/lib/python3.6/site-packages/conda/common/logic.py:172(run)
    40808    0.265    0.000    8.912    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/index.py:188(push_record)
   126052    1.796    0.000    8.722    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/models/match_spec.py:446(merge)
599366/577926    5.844    0.000    8.308    0.000 {built-in method builtins.next}
197139/6175    0.475    0.000    7.670    0.001 /home/dm/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py:718(__call__)
197139/6175    1.586    0.000    7.611    0.001 /home/dm/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py:733(__init__)
51807/49934    0.154    0.000    7.281    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/resolve.py:550(push_MatchSpec)
710933/135162    0.434    0.000    7.247    0.000 {built-in method builtins.setattr}
510122/125315    0.859    0.000    7.149    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py:422(__set__)
        3    0.000    0.000    7.101    2.367 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/prefix_data.py:106(get)
        9    0.000    0.000    7.101    0.789 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/prefix_data.py:143(_prefix_records)
        1    0.036    0.036    7.101    7.101 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/prefix_data.py:62(load)
      824    0.027    0.000    7.059    0.009 /home/dm/anaconda3/lib/python3.6/site-packages/conda/core/prefix_data.py:147(_load_single_record)
  5727599    6.487    0.000    6.487    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/models/match_spec.py:794(match)
     9452    0.019    0.000    6.353    0.001 /home/dm/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py:651(box)
    26226    0.091    0.000    6.350    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py:581(box)
   467590    1.192    0.000    6.318    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/models/match_spec.py:31(__call__)
   190140    0.270    0.000    6.162    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py:590(<genexpr>)
302706/199337    0.143    0.000    5.826    0.000 {built-in method builtins.all}
   101204    0.091    0.000    5.814    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/resolve.py:467(find_matches)
 13896156    3.749    0.000    5.751    0.000 {method 'get' of 'dict' objects}
     3448    0.138    0.000    5.686    0.002 /home/dm/anaconda3/lib/python3.6/site-packages/conda/resolve.py:574(<listcomp>)
       70    0.001    0.000    5.583    0.080 /home/dm/anaconda3/lib/python3.6/site-packages/conda/common/logic.py:207(invoke)
   401664    0.308    0.000    5.331    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/models/match_spec.py:448(<genexpr>)
  6045066    3.005    0.000    4.958    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/common/compat.py:84(iteritems)
  593/329    0.113    0.000    4.916    0.015 /home/dm/anaconda3/lib/python3.6/site-packages/conda/resolve.py:334(filter_group)
   558628    0.619    0.000    4.433    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/models/version.py:465(operator_match)
  1940885    2.857    0.000    4.316    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/common/logic.py:500(ITE_)
    45367    0.150    0.000    4.273    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/resolve.py:488(ms_depends)
     7243    0.034    0.000    4.270    0.001 /home/dm/anaconda3/lib/python3.6/site-packages/conda/resolve.py:439(<genexpr>)
    16085    0.200    0.000    4.222    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/resolve.py:124(valid2)
   334168    0.613    0.000    4.193    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/models/match_spec.py:168(__init__)
   296455    0.364    0.000    4.151    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/models/version.py:471(all_match)
    16085    0.011    0.000    4.022    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/resolve.py:125(is_valid)
101609/16085    0.055    0.000    4.003    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/resolve.py:136(is_valid_prec)
       70    0.003    0.000    3.888    0.056 /home/dm/anaconda3/lib/python3.6/site-packages/conda/common/logic.py:197(setup)
       70    3.884    0.055    3.884    0.055 {built-in method pycosat.itersolve}
   711539    0.290    0.000    3.651    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/models/version.py:472(<genexpr>)
    35817    0.094    0.000    3.644    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/resolve.py:484(<genexpr>)
   334168    1.429    0.000    3.506    0.000 /home/dm/anaconda3/lib/python3.6/site-packages/conda/models/match_spec.py:380(_build_components)
       36    3.465    0.096    3.465    0.096 {method 'poll' of 'select.poll' objects}
       33    0.000    0.000    3.371    0.102 /home/dm/anaconda3/lib/python3.6/site-packages/urllib3/util/wait.py:139(wait_for_read)
       33    0.001    0.000    3.371    0.102 /home/dm/anaconda3/lib/python3.6/site-packages/urllib3/util/wait.py:87(poll_wait_for_socket)
       34    0.000    0.000    3.370    0.099 /home/dm/anaconda3/lib/python3.6/site-packages/urllib3/util/wait.py:41(_retry_on_intr)


Out[7]: <pstats.Stats at 0x7fb1fe43f748>
````

**Comment by rth** [comment]
> I have set up Airspeed Velocity for conda with some simple, very high level benchmarks

The graphs look quite useful. Just to clarify, when we see something like,
![asv_example](https://user-images.githubusercontent.com/630936/51537559-2f84e900-1e4f-11e9-9abf-fd6f8af1ac22.png)

does it mean that the changes are exclusively due to changes in conda package, or do they also account for the fact that the dependency tree could have evolved in the mean time (at the very least there are new package releases)?

**Comment by msarahan** [comment]
We download the repodata once and have it cached locally.  Any changes in the graph should reflect code changes in conda, not changes in the repodata.

If we ever change the repodata (which may be desirable to capture hotfixes or otherwise better reflect the current size of the ecosystem), we would need to re-run the entire history of benchmarks.

**Comment by reedacartwright** [comment]
FreeBSD's package manager has spent a lot of effort on their dependency solver. Maybe their work is useful for conda. https://github.com/freebsd/pkg

**Comment by ctb** [comment]
See also: https://github.com/bioconda/bioconda-recipes/issues/13774.

**Comment by mbargull** [comment]
> Note that each commit takes about 10 min to run. It's going to take a very long time to fully populate this graph.

Maybe you can set it to only run for tagged commits and merge commits on `master` (and/or the current release branch, e.g., `4.6.x`)?

> Still, I hope the benchmarking code is perhaps useful

For sure! Looks nice, thanks for setting that up!

**Comment by travishathaway** [comment]
Considering that all the issues linked to in the issue description are complete, I will be closing this issue 🎉 . Please re-open and comment if you disagree.

**Comment by jaimergp** [comment]
Yea, I don't know how to feel about auto-closing feature requests... Maybe a discussion worth its own issue.

**Comment by emanueol** [comment]
Yesterday I got surprised by time anaconda solver was taking (default anaconda windows installation i did some months ago, no packages installed on base environment, and just 2 very small test environments) it was taking hours, and just needed update a version:
```
    ==> WARNING: A newer version of conda exists. <==
      current version: 23.7.4
      latest version: 24.1.2
  
    Please update conda by running
        $ conda update -n base -c defaults conda

    Or to minimize the number of packages updated during conda update use
         conda install conda=24.9.1
```


Both commands suggested and all online forums suggested:
```
$ conda update -n base conda

$ conda update -n base -c defaults conda
$ conda install conda=24.9.1
$ conda install -n base -c defaults 'conda>=24.9.1'
```

So clear something very wrong, and this is out of the box anaconda installation that i just fired what i thought would be simple/fas operation:
`$ conda update -n base conda`

Soon discovered massive number of posts online broadcasting this pr

**Comment by abalter** [comment]
@emanueol --- dude, no one uses the native solver anymore. And most people don't bother with the Anaconda versions at all.

[`{micromamba}`](https://mamba.readthedocs.io/en/latest) is the future, and it's already here!

**Comment by emanueol** [comment]
> [@emanueol](https://github.com/emanueol) --- dude, no one uses the native solver anymore. And most people don't bother with the Anaconda versions at all.
> 
> [`{micromamba}`](https://mamba.readthedocs.io/en/latest) is the future, and it's already here!

thanks man 😊 for the feedback, i saw mamba solver of client in sone suggestions, just wanted double check

**Comment by abalter** [comment]
I've been thinking it's time for me to write an article about the conda-verse to help people out. Maybe on medium or something.
